// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fighter/via_svc.proto

package com.platon.rosettanet.admin.grpc;

public final class ViaProviderRpcMessage {
  private ViaProviderRpcMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code viasvc.ServiceType}
   */
  public enum ServiceType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DATA_SVC = 0;</code>
     */
    DATA_SVC(0),
    /**
     * <code>COMPUTE_SVC = 1;</code>
     */
    COMPUTE_SVC(1),
    /**
     * <code>SCHEDULE_SVC = 2;</code>
     */
    SCHEDULE_SVC(2),
    /**
     * <code>NET_COMM_SVC = 3;</code>
     */
    NET_COMM_SVC(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>DATA_SVC = 0;</code>
     */
    public static final int DATA_SVC_VALUE = 0;
    /**
     * <code>COMPUTE_SVC = 1;</code>
     */
    public static final int COMPUTE_SVC_VALUE = 1;
    /**
     * <code>SCHEDULE_SVC = 2;</code>
     */
    public static final int SCHEDULE_SVC_VALUE = 2;
    /**
     * <code>NET_COMM_SVC = 3;</code>
     */
    public static final int NET_COMM_SVC_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ServiceType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ServiceType forNumber(int value) {
      switch (value) {
        case 0: return DATA_SVC;
        case 1: return COMPUTE_SVC;
        case 2: return SCHEDULE_SVC;
        case 3: return NET_COMM_SVC;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ServiceType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ServiceType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ServiceType>() {
            public ServiceType findValueByNumber(int number) {
              return ServiceType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final ServiceType[] VALUES = values();

    public static ServiceType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ServiceType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:viasvc.ServiceType)
  }

  public interface ExposeReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:viasvc.ExposeReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string task_id = 1;</code>
     * @return The taskId.
     */
    java.lang.String getTaskId();
    /**
     * <code>string task_id = 1;</code>
     * @return The bytes for taskId.
     */
    com.google.protobuf.ByteString
        getTaskIdBytes();

    /**
     * <code>.viasvc.ServiceType svc_type = 2;</code>
     * @return The enum numeric value on the wire for svcType.
     */
    int getSvcTypeValue();
    /**
     * <code>.viasvc.ServiceType svc_type = 2;</code>
     * @return The svcType.
     */
    com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ServiceType getSvcType();

    /**
     * <code>string party_id = 3;</code>
     * @return The partyId.
     */
    java.lang.String getPartyId();
    /**
     * <code>string party_id = 3;</code>
     * @return The bytes for partyId.
     */
    com.google.protobuf.ByteString
        getPartyIdBytes();

    /**
     * <code>string ip = 4;</code>
     * @return The ip.
     */
    java.lang.String getIp();
    /**
     * <code>string ip = 4;</code>
     * @return The bytes for ip.
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <code>int32 port = 5;</code>
     * @return The port.
     */
    int getPort();
  }
  /**
   * Protobuf type {@code viasvc.ExposeReq}
   */
  public static final class ExposeReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:viasvc.ExposeReq)
      ExposeReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ExposeReq.newBuilder() to construct.
    private ExposeReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ExposeReq() {
      taskId_ = "";
      svcType_ = 0;
      partyId_ = "";
      ip_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ExposeReq();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ExposeReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              taskId_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              svcType_ = rawValue;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              partyId_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              ip_ = s;
              break;
            }
            case 40: {

              port_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.internal_static_viasvc_ExposeReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.internal_static_viasvc_ExposeReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeReq.class, com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeReq.Builder.class);
    }

    public static final int TASK_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object taskId_;
    /**
     * <code>string task_id = 1;</code>
     * @return The taskId.
     */
    @java.lang.Override
    public java.lang.String getTaskId() {
      java.lang.Object ref = taskId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskId_ = s;
        return s;
      }
    }
    /**
     * <code>string task_id = 1;</code>
     * @return The bytes for taskId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTaskIdBytes() {
      java.lang.Object ref = taskId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SVC_TYPE_FIELD_NUMBER = 2;
    private int svcType_;
    /**
     * <code>.viasvc.ServiceType svc_type = 2;</code>
     * @return The enum numeric value on the wire for svcType.
     */
    @java.lang.Override public int getSvcTypeValue() {
      return svcType_;
    }
    /**
     * <code>.viasvc.ServiceType svc_type = 2;</code>
     * @return The svcType.
     */
    @java.lang.Override public com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ServiceType getSvcType() {
      @SuppressWarnings("deprecation")
      com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ServiceType result = com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ServiceType.valueOf(svcType_);
      return result == null ? com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ServiceType.UNRECOGNIZED : result;
    }

    public static final int PARTY_ID_FIELD_NUMBER = 3;
    private volatile java.lang.Object partyId_;
    /**
     * <code>string party_id = 3;</code>
     * @return The partyId.
     */
    @java.lang.Override
    public java.lang.String getPartyId() {
      java.lang.Object ref = partyId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        partyId_ = s;
        return s;
      }
    }
    /**
     * <code>string party_id = 3;</code>
     * @return The bytes for partyId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPartyIdBytes() {
      java.lang.Object ref = partyId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        partyId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IP_FIELD_NUMBER = 4;
    private volatile java.lang.Object ip_;
    /**
     * <code>string ip = 4;</code>
     * @return The ip.
     */
    @java.lang.Override
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      }
    }
    /**
     * <code>string ip = 4;</code>
     * @return The bytes for ip.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 5;
    private int port_;
    /**
     * <code>int32 port = 5;</code>
     * @return The port.
     */
    @java.lang.Override
    public int getPort() {
      return port_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTaskIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, taskId_);
      }
      if (svcType_ != com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ServiceType.DATA_SVC.getNumber()) {
        output.writeEnum(2, svcType_);
      }
      if (!getPartyIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, partyId_);
      }
      if (!getIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, ip_);
      }
      if (port_ != 0) {
        output.writeInt32(5, port_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTaskIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, taskId_);
      }
      if (svcType_ != com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ServiceType.DATA_SVC.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, svcType_);
      }
      if (!getPartyIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, partyId_);
      }
      if (!getIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, ip_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, port_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeReq)) {
        return super.equals(obj);
      }
      com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeReq other = (com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeReq) obj;

      if (!getTaskId()
          .equals(other.getTaskId())) return false;
      if (svcType_ != other.svcType_) return false;
      if (!getPartyId()
          .equals(other.getPartyId())) return false;
      if (!getIp()
          .equals(other.getIp())) return false;
      if (getPort()
          != other.getPort()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TASK_ID_FIELD_NUMBER;
      hash = (53 * hash) + getTaskId().hashCode();
      hash = (37 * hash) + SVC_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + svcType_;
      hash = (37 * hash) + PARTY_ID_FIELD_NUMBER;
      hash = (53 * hash) + getPartyId().hashCode();
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + getIp().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code viasvc.ExposeReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:viasvc.ExposeReq)
        com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.internal_static_viasvc_ExposeReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.internal_static_viasvc_ExposeReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeReq.class, com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeReq.Builder.class);
      }

      // Construct using com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        taskId_ = "";

        svcType_ = 0;

        partyId_ = "";

        ip_ = "";

        port_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.internal_static_viasvc_ExposeReq_descriptor;
      }

      @java.lang.Override
      public com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeReq getDefaultInstanceForType() {
        return com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeReq.getDefaultInstance();
      }

      @java.lang.Override
      public com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeReq build() {
        com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeReq buildPartial() {
        com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeReq result = new com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeReq(this);
        result.taskId_ = taskId_;
        result.svcType_ = svcType_;
        result.partyId_ = partyId_;
        result.ip_ = ip_;
        result.port_ = port_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeReq) {
          return mergeFrom((com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeReq other) {
        if (other == com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeReq.getDefaultInstance()) return this;
        if (!other.getTaskId().isEmpty()) {
          taskId_ = other.taskId_;
          onChanged();
        }
        if (other.svcType_ != 0) {
          setSvcTypeValue(other.getSvcTypeValue());
        }
        if (!other.getPartyId().isEmpty()) {
          partyId_ = other.partyId_;
          onChanged();
        }
        if (!other.getIp().isEmpty()) {
          ip_ = other.ip_;
          onChanged();
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object taskId_ = "";
      /**
       * <code>string task_id = 1;</code>
       * @return The taskId.
       */
      public java.lang.String getTaskId() {
        java.lang.Object ref = taskId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          taskId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string task_id = 1;</code>
       * @return The bytes for taskId.
       */
      public com.google.protobuf.ByteString
          getTaskIdBytes() {
        java.lang.Object ref = taskId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          taskId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string task_id = 1;</code>
       * @param value The taskId to set.
       * @return This builder for chaining.
       */
      public Builder setTaskId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        taskId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string task_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTaskId() {
        
        taskId_ = getDefaultInstance().getTaskId();
        onChanged();
        return this;
      }
      /**
       * <code>string task_id = 1;</code>
       * @param value The bytes for taskId to set.
       * @return This builder for chaining.
       */
      public Builder setTaskIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        taskId_ = value;
        onChanged();
        return this;
      }

      private int svcType_ = 0;
      /**
       * <code>.viasvc.ServiceType svc_type = 2;</code>
       * @return The enum numeric value on the wire for svcType.
       */
      @java.lang.Override public int getSvcTypeValue() {
        return svcType_;
      }
      /**
       * <code>.viasvc.ServiceType svc_type = 2;</code>
       * @param value The enum numeric value on the wire for svcType to set.
       * @return This builder for chaining.
       */
      public Builder setSvcTypeValue(int value) {
        
        svcType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.viasvc.ServiceType svc_type = 2;</code>
       * @return The svcType.
       */
      @java.lang.Override
      public com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ServiceType getSvcType() {
        @SuppressWarnings("deprecation")
        com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ServiceType result = com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ServiceType.valueOf(svcType_);
        return result == null ? com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ServiceType.UNRECOGNIZED : result;
      }
      /**
       * <code>.viasvc.ServiceType svc_type = 2;</code>
       * @param value The svcType to set.
       * @return This builder for chaining.
       */
      public Builder setSvcType(com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ServiceType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        svcType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.viasvc.ServiceType svc_type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSvcType() {
        
        svcType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object partyId_ = "";
      /**
       * <code>string party_id = 3;</code>
       * @return The partyId.
       */
      public java.lang.String getPartyId() {
        java.lang.Object ref = partyId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          partyId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string party_id = 3;</code>
       * @return The bytes for partyId.
       */
      public com.google.protobuf.ByteString
          getPartyIdBytes() {
        java.lang.Object ref = partyId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          partyId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string party_id = 3;</code>
       * @param value The partyId to set.
       * @return This builder for chaining.
       */
      public Builder setPartyId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        partyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string party_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPartyId() {
        
        partyId_ = getDefaultInstance().getPartyId();
        onChanged();
        return this;
      }
      /**
       * <code>string party_id = 3;</code>
       * @param value The bytes for partyId to set.
       * @return This builder for chaining.
       */
      public Builder setPartyIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        partyId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ip_ = "";
      /**
       * <code>string ip = 4;</code>
       * @return The ip.
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ip = 4;</code>
       * @return The bytes for ip.
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ip = 4;</code>
       * @param value The ip to set.
       * @return This builder for chaining.
       */
      public Builder setIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ip = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearIp() {
        
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>string ip = 4;</code>
       * @param value The bytes for ip to set.
       * @return This builder for chaining.
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ip_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>int32 port = 5;</code>
       * @return The port.
       */
      @java.lang.Override
      public int getPort() {
        return port_;
      }
      /**
       * <code>int32 port = 5;</code>
       * @param value The port to set.
       * @return This builder for chaining.
       */
      public Builder setPort(int value) {
        
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 port = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPort() {
        
        port_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:viasvc.ExposeReq)
    }

    // @@protoc_insertion_point(class_scope:viasvc.ExposeReq)
    private static final com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeReq();
    }

    public static com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ExposeReq>
        PARSER = new com.google.protobuf.AbstractParser<ExposeReq>() {
      @java.lang.Override
      public ExposeReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExposeReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ExposeReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ExposeReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ExposeAnsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:viasvc.ExposeAns)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool ok = 1;</code>
     * @return The ok.
     */
    boolean getOk();

    /**
     * <code>string ip = 2;</code>
     * @return The ip.
     */
    java.lang.String getIp();
    /**
     * <code>string ip = 2;</code>
     * @return The bytes for ip.
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <code>int32 port = 3;</code>
     * @return The port.
     */
    int getPort();
  }
  /**
   * Protobuf type {@code viasvc.ExposeAns}
   */
  public static final class ExposeAns extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:viasvc.ExposeAns)
      ExposeAnsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ExposeAns.newBuilder() to construct.
    private ExposeAns(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ExposeAns() {
      ip_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ExposeAns();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ExposeAns(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              ok_ = input.readBool();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              ip_ = s;
              break;
            }
            case 24: {

              port_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.internal_static_viasvc_ExposeAns_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.internal_static_viasvc_ExposeAns_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeAns.class, com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeAns.Builder.class);
    }

    public static final int OK_FIELD_NUMBER = 1;
    private boolean ok_;
    /**
     * <code>bool ok = 1;</code>
     * @return The ok.
     */
    @java.lang.Override
    public boolean getOk() {
      return ok_;
    }

    public static final int IP_FIELD_NUMBER = 2;
    private volatile java.lang.Object ip_;
    /**
     * <code>string ip = 2;</code>
     * @return The ip.
     */
    @java.lang.Override
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      }
    }
    /**
     * <code>string ip = 2;</code>
     * @return The bytes for ip.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 3;
    private int port_;
    /**
     * <code>int32 port = 3;</code>
     * @return The port.
     */
    @java.lang.Override
    public int getPort() {
      return port_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (ok_ != false) {
        output.writeBool(1, ok_);
      }
      if (!getIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ip_);
      }
      if (port_ != 0) {
        output.writeInt32(3, port_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (ok_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, ok_);
      }
      if (!getIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, ip_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, port_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeAns)) {
        return super.equals(obj);
      }
      com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeAns other = (com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeAns) obj;

      if (getOk()
          != other.getOk()) return false;
      if (!getIp()
          .equals(other.getIp())) return false;
      if (getPort()
          != other.getPort()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getOk());
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + getIp().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeAns parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeAns parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeAns parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeAns parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeAns parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeAns parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeAns parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeAns parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeAns parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeAns parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeAns parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeAns parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeAns prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code viasvc.ExposeAns}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:viasvc.ExposeAns)
        com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeAnsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.internal_static_viasvc_ExposeAns_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.internal_static_viasvc_ExposeAns_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeAns.class, com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeAns.Builder.class);
      }

      // Construct using com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeAns.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        ok_ = false;

        ip_ = "";

        port_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.internal_static_viasvc_ExposeAns_descriptor;
      }

      @java.lang.Override
      public com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeAns getDefaultInstanceForType() {
        return com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeAns.getDefaultInstance();
      }

      @java.lang.Override
      public com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeAns build() {
        com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeAns result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeAns buildPartial() {
        com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeAns result = new com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeAns(this);
        result.ok_ = ok_;
        result.ip_ = ip_;
        result.port_ = port_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeAns) {
          return mergeFrom((com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeAns)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeAns other) {
        if (other == com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeAns.getDefaultInstance()) return this;
        if (other.getOk() != false) {
          setOk(other.getOk());
        }
        if (!other.getIp().isEmpty()) {
          ip_ = other.ip_;
          onChanged();
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeAns parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeAns) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean ok_ ;
      /**
       * <code>bool ok = 1;</code>
       * @return The ok.
       */
      @java.lang.Override
      public boolean getOk() {
        return ok_;
      }
      /**
       * <code>bool ok = 1;</code>
       * @param value The ok to set.
       * @return This builder for chaining.
       */
      public Builder setOk(boolean value) {
        
        ok_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool ok = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOk() {
        
        ok_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object ip_ = "";
      /**
       * <code>string ip = 2;</code>
       * @return The ip.
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ip = 2;</code>
       * @return The bytes for ip.
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ip = 2;</code>
       * @param value The ip to set.
       * @return This builder for chaining.
       */
      public Builder setIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ip = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearIp() {
        
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>string ip = 2;</code>
       * @param value The bytes for ip to set.
       * @return This builder for chaining.
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ip_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>int32 port = 3;</code>
       * @return The port.
       */
      @java.lang.Override
      public int getPort() {
        return port_;
      }
      /**
       * <code>int32 port = 3;</code>
       * @param value The port to set.
       * @return This builder for chaining.
       */
      public Builder setPort(int value) {
        
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 port = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPort() {
        
        port_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:viasvc.ExposeAns)
    }

    // @@protoc_insertion_point(class_scope:viasvc.ExposeAns)
    private static final com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeAns DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeAns();
    }

    public static com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeAns getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ExposeAns>
        PARSER = new com.google.protobuf.AbstractParser<ExposeAns>() {
      @java.lang.Override
      public ExposeAns parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExposeAns(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ExposeAns> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ExposeAns> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.platon.rosettanet.admin.grpc.ViaProviderRpcMessage.ExposeAns getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_viasvc_ExposeReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_viasvc_ExposeReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_viasvc_ExposeAns_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_viasvc_ExposeAns_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025fighter/via_svc.proto\022\006viasvc\"o\n\tExpos" +
      "eReq\022\017\n\007task_id\030\001 \001(\t\022%\n\010svc_type\030\002 \001(\0162" +
      "\023.viasvc.ServiceType\022\020\n\010party_id\030\003 \001(\t\022\n" +
      "\n\002ip\030\004 \001(\t\022\014\n\004port\030\005 \001(\005\"1\n\tExposeAns\022\n\n" +
      "\002ok\030\001 \001(\010\022\n\n\002ip\030\002 \001(\t\022\014\n\004port\030\003 \001(\005*P\n\013S" +
      "erviceType\022\014\n\010DATA_SVC\020\000\022\017\n\013COMPUTE_SVC\020" +
      "\001\022\020\n\014SCHEDULE_SVC\020\002\022\020\n\014NET_COMM_SVC\020\0032n\n" +
      "\013ViaProvider\0220\n\006Expose\022\021.viasvc.ExposeRe" +
      "q\032\021.viasvc.ExposeAns\"\000\022-\n\003Off\022\021.viasvc.E" +
      "xposeReq\032\021.viasvc.ExposeAns\"\000B9\n com.pla" +
      "ton.rosettanet.admin.grpcB\025ViaProviderRp" +
      "cMessageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_viasvc_ExposeReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_viasvc_ExposeReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_viasvc_ExposeReq_descriptor,
        new java.lang.String[] { "TaskId", "SvcType", "PartyId", "Ip", "Port", });
    internal_static_viasvc_ExposeAns_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_viasvc_ExposeAns_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_viasvc_ExposeAns_descriptor,
        new java.lang.String[] { "Ok", "Ip", "Port", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
