// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lib/common/base.proto

package com.platon.rosettanet.admin.grpc.service;

/**
 * Protobuf enum {@code api.protobuf.AuditMetadataOption}
 */
public enum AuditMetadataOption
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * 等待审核中
   * </pre>
   *
   * <code>Audit_Pending = 0;</code>
   */
  Audit_Pending(0),
  /**
   * <pre>
   * 审核通过
   * </pre>
   *
   * <code>Audit_Passed = 1;</code>
   */
  Audit_Passed(1),
  /**
   * <pre>
   * 审核拒绝
   * </pre>
   *
   * <code>Audit_Refused = 2;</code>
   */
  Audit_Refused(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * 等待审核中
   * </pre>
   *
   * <code>Audit_Pending = 0;</code>
   */
  public static final int Audit_Pending_VALUE = 0;
  /**
   * <pre>
   * 审核通过
   * </pre>
   *
   * <code>Audit_Passed = 1;</code>
   */
  public static final int Audit_Passed_VALUE = 1;
  /**
   * <pre>
   * 审核拒绝
   * </pre>
   *
   * <code>Audit_Refused = 2;</code>
   */
  public static final int Audit_Refused_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static AuditMetadataOption valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static AuditMetadataOption forNumber(int value) {
    switch (value) {
      case 0: return Audit_Pending;
      case 1: return Audit_Passed;
      case 2: return Audit_Refused;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<AuditMetadataOption>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      AuditMetadataOption> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<AuditMetadataOption>() {
          public AuditMetadataOption findValueByNumber(int number) {
            return AuditMetadataOption.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.platon.rosettanet.admin.grpc.service.Base.getDescriptor().getEnumTypes().get(3);
  }

  private static final AuditMetadataOption[] VALUES = values();

  public static AuditMetadataOption valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private AuditMetadataOption(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:api.protobuf.AuditMetadataOption)
}

