// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lib/types/metadata.proto

package com.platon.rosettanet.admin.grpc.service;

public interface AuthRecordPBOrBuilder extends
    // @@protoc_insertion_point(interface_extends:types.AuthRecordPB)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 申请记录ID
   * </pre>
   *
   * <code>string auth_record_id = 1;</code>
   * @return The authRecordId.
   */
  java.lang.String getAuthRecordId();
  /**
   * <pre>
   * 申请记录ID
   * </pre>
   *
   * <code>string auth_record_id = 1;</code>
   * @return The bytes for authRecordId.
   */
  com.google.protobuf.ByteString
      getAuthRecordIdBytes();

  /**
   * <pre>
   * 申请人地址
   * </pre>
   *
   * <code>string user = 2;</code>
   * @return The user.
   */
  java.lang.String getUser();
  /**
   * <pre>
   * 申请人地址
   * </pre>
   *
   * <code>string user = 2;</code>
   * @return The bytes for user.
   */
  com.google.protobuf.ByteString
      getUserBytes();

  /**
   * <pre>
   * 申请人类型
   * </pre>
   *
   * <code>.api.protobuf.UserType user_type = 3;</code>
   * @return The enum numeric value on the wire for userType.
   */
  int getUserTypeValue();
  /**
   * <pre>
   * 申请人类型
   * </pre>
   *
   * <code>.api.protobuf.UserType user_type = 3;</code>
   * @return The userType.
   */
  com.platon.rosettanet.admin.grpc.service.UserType getUserType();

  /**
   * <pre>
   * 申请的数据
   * </pre>
   *
   * <code>.types.MetadataAuthority data_record = 4;</code>
   * @return Whether the dataRecord field is set.
   */
  boolean hasDataRecord();
  /**
   * <pre>
   * 申请的数据
   * </pre>
   *
   * <code>.types.MetadataAuthority data_record = 4;</code>
   * @return The dataRecord.
   */
  com.platon.rosettanet.admin.grpc.service.MetadataAuthority getDataRecord();
  /**
   * <pre>
   * 申请的数据
   * </pre>
   *
   * <code>.types.MetadataAuthority data_record = 4;</code>
   */
  com.platon.rosettanet.admin.grpc.service.MetadataAuthorityOrBuilder getDataRecordOrBuilder();

  /**
   * <pre>
   * 审核结果
   * </pre>
   *
   * <code>.api.protobuf.AuditMetadataOption audit_result = 5;</code>
   * @return The enum numeric value on the wire for auditResult.
   */
  int getAuditResultValue();
  /**
   * <pre>
   * 审核结果
   * </pre>
   *
   * <code>.api.protobuf.AuditMetadataOption audit_result = 5;</code>
   * @return The auditResult.
   */
  com.platon.rosettanet.admin.grpc.service.AuditMetadataOption getAuditResult();

  /**
   * <pre>
   * 审核意见
   * </pre>
   *
   * <code>string audit_suggest = 6;</code>
   * @return The auditSuggest.
   */
  java.lang.String getAuditSuggest();
  /**
   * <pre>
   * 审核意见
   * </pre>
   *
   * <code>string audit_suggest = 6;</code>
   * @return The bytes for auditSuggest.
   */
  com.google.protobuf.ByteString
      getAuditSuggestBytes();

  /**
   * <pre>
   * 发起授权申请的时间 (单位: ms)
   * </pre>
   *
   * <code>uint64 apply_at = 7;</code>
   * @return The applyAt.
   */
  long getApplyAt();

  /**
   * <pre>
   * 审核授权申请的时间 (单位: ms)
   * </pre>
   *
   * <code>uint64 audit_at = 8;</code>
   * @return The auditAt.
   */
  long getAuditAt();
}
