// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lib/types/identitydata.proto

package com.platon.rosettanet.admin.grpc.service;

public final class IdentityDataProto {
  private IdentityDataProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_IdentityPB_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_IdentityPB_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034lib/types/identitydata.proto\022\005types\032\025l" +
      "ib/common/base.proto\"\305\001\n\nIdentityPB\022\023\n\013i" +
      "dentity_id\030\001 \001(\t\022\017\n\007node_id\030\002 \001(\t\022\021\n\tnod" +
      "e_name\030\003 \001(\t\022\017\n\007data_id\030\004 \001(\t\022-\n\013data_st" +
      "atus\030\005 \001(\0162\030.api.protobuf.DataStatus\022*\n\006" +
      "status\030\006 \001(\0162\032.api.protobuf.CommonStatus" +
      "\022\022\n\ncredential\030\007 \001(\tB?\n(com.platon.roset" +
      "tanet.admin.grpc.serviceB\021IdentityDataPr" +
      "otoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.platon.rosettanet.admin.grpc.service.Base.getDescriptor(),
        });
    internal_static_types_IdentityPB_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_types_IdentityPB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_IdentityPB_descriptor,
        new java.lang.String[] { "IdentityId", "NodeId", "NodeName", "DataId", "DataStatus", "Status", "Credential", });
    com.platon.rosettanet.admin.grpc.service.Base.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
