// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lib/types/identitydata.proto

package com.platon.rosettanet.admin.grpc.service;

public interface IdentityPBOrBuilder extends
    // @@protoc_insertion_point(interface_extends:types.IdentityPB)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string identity_id = 1;</code>
   * @return The identityId.
   */
  java.lang.String getIdentityId();
  /**
   * <code>string identity_id = 1;</code>
   * @return The bytes for identityId.
   */
  com.google.protobuf.ByteString
      getIdentityIdBytes();

  /**
   * <code>string node_id = 2;</code>
   * @return The nodeId.
   */
  java.lang.String getNodeId();
  /**
   * <code>string node_id = 2;</code>
   * @return The bytes for nodeId.
   */
  com.google.protobuf.ByteString
      getNodeIdBytes();

  /**
   * <code>string node_name = 3;</code>
   * @return The nodeName.
   */
  java.lang.String getNodeName();
  /**
   * <code>string node_name = 3;</code>
   * @return The bytes for nodeName.
   */
  com.google.protobuf.ByteString
      getNodeNameBytes();

  /**
   * <code>string data_id = 4;</code>
   * @return The dataId.
   */
  java.lang.String getDataId();
  /**
   * <code>string data_id = 4;</code>
   * @return The bytes for dataId.
   */
  com.google.protobuf.ByteString
      getDataIdBytes();

  /**
   * <pre>
   * N means normal, D means deleted
   * </pre>
   *
   * <code>.api.protobuf.DataStatus data_status = 5;</code>
   * @return The enum numeric value on the wire for dataStatus.
   */
  int getDataStatusValue();
  /**
   * <pre>
   * N means normal, D means deleted
   * </pre>
   *
   * <code>.api.protobuf.DataStatus data_status = 5;</code>
   * @return The dataStatus.
   */
  com.platon.rosettanet.admin.grpc.service.DataStatus getDataStatus();

  /**
   * <pre>
   * Y : normal, N non-normal
   * </pre>
   *
   * <code>.api.protobuf.CommonStatus status = 6;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <pre>
   * Y : normal, N non-normal
   * </pre>
   *
   * <code>.api.protobuf.CommonStatus status = 6;</code>
   * @return The status.
   */
  com.platon.rosettanet.admin.grpc.service.CommonStatus getStatus();

  /**
   * <pre>
   * json format for credential
   * </pre>
   *
   * <code>string credential = 7;</code>
   * @return The credential.
   */
  java.lang.String getCredential();
  /**
   * <pre>
   * json format for credential
   * </pre>
   *
   * <code>string credential = 7;</code>
   * @return The bytes for credential.
   */
  com.google.protobuf.ByteString
      getCredentialBytes();
}
