// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lib/types/resourcedata.proto

package com.platon.rosettanet.admin.grpc.service;

/**
 * <pre>
 * 单个组织中的单台服务的算力信息
 * </pre>
 *
 * Protobuf type {@code types.LocalResourcePB}
 */
public final class LocalResourcePB extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:types.LocalResourcePB)
    LocalResourcePBOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LocalResourcePB.newBuilder() to construct.
  private LocalResourcePB(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LocalResourcePB() {
    identityId_ = "";
    nodeId_ = "";
    nodeName_ = "";
    jobNodeId_ = "";
    dataId_ = "";
    dataStatus_ = 0;
    state_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new LocalResourcePB();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LocalResourcePB(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            identityId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            nodeId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            nodeName_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            jobNodeId_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            dataId_ = s;
            break;
          }
          case 48: {
            int rawValue = input.readEnum();

            dataStatus_ = rawValue;
            break;
          }
          case 56: {
            int rawValue = input.readEnum();

            state_ = rawValue;
            break;
          }
          case 64: {

            totalMem_ = input.readUInt64();
            break;
          }
          case 72: {

            usedMem_ = input.readUInt64();
            break;
          }
          case 80: {

            totalProcessor_ = input.readUInt32();
            break;
          }
          case 88: {

            usedProcessor_ = input.readUInt32();
            break;
          }
          case 96: {

            totalBandwidth_ = input.readUInt64();
            break;
          }
          case 104: {

            usedBandwidth_ = input.readUInt64();
            break;
          }
          case 112: {

            totalDisk_ = input.readUInt64();
            break;
          }
          case 120: {

            usedDisk_ = input.readUInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.platon.rosettanet.admin.grpc.service.ResourceDataProto.internal_static_types_LocalResourcePB_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.platon.rosettanet.admin.grpc.service.ResourceDataProto.internal_static_types_LocalResourcePB_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.platon.rosettanet.admin.grpc.service.LocalResourcePB.class, com.platon.rosettanet.admin.grpc.service.LocalResourcePB.Builder.class);
  }

  public static final int IDENTITY_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object identityId_;
  /**
   * <pre>
   * 算力所属的组织的 身份标识
   * </pre>
   *
   * <code>string identity_id = 1;</code>
   * @return The identityId.
   */
  @java.lang.Override
  public java.lang.String getIdentityId() {
    java.lang.Object ref = identityId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      identityId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 算力所属的组织的 身份标识
   * </pre>
   *
   * <code>string identity_id = 1;</code>
   * @return The bytes for identityId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdentityIdBytes() {
    java.lang.Object ref = identityId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      identityId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NODE_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object nodeId_;
  /**
   * <pre>
   * 算力所属的组织的 p2p公钥
   * </pre>
   *
   * <code>string node_id = 2;</code>
   * @return The nodeId.
   */
  @java.lang.Override
  public java.lang.String getNodeId() {
    java.lang.Object ref = nodeId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nodeId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 算力所属的组织的 p2p公钥
   * </pre>
   *
   * <code>string node_id = 2;</code>
   * @return The bytes for nodeId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNodeIdBytes() {
    java.lang.Object ref = nodeId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nodeId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NODE_NAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object nodeName_;
  /**
   * <pre>
   * 算力所属的组织的 组织名称
   * </pre>
   *
   * <code>string node_name = 3;</code>
   * @return The nodeName.
   */
  @java.lang.Override
  public java.lang.String getNodeName() {
    java.lang.Object ref = nodeName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nodeName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 算力所属的组织的 组织名称
   * </pre>
   *
   * <code>string node_name = 3;</code>
   * @return The bytes for nodeName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNodeNameBytes() {
    java.lang.Object ref = nodeName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nodeName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int JOB_NODE_ID_FIELD_NUMBER = 4;
  private volatile java.lang.Object jobNodeId_;
  /**
   * <pre>
   * 算力对应的内部计算服务的jobNodeId
   * </pre>
   *
   * <code>string job_node_id = 4;</code>
   * @return The jobNodeId.
   */
  @java.lang.Override
  public java.lang.String getJobNodeId() {
    java.lang.Object ref = jobNodeId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      jobNodeId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 算力对应的内部计算服务的jobNodeId
   * </pre>
   *
   * <code>string job_node_id = 4;</code>
   * @return The bytes for jobNodeId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getJobNodeIdBytes() {
    java.lang.Object ref = jobNodeId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      jobNodeId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATA_ID_FIELD_NUMBER = 5;
  private volatile java.lang.Object dataId_;
  /**
   * <pre>
   * 算力的powerId
   * </pre>
   *
   * <code>string data_id = 5;</code>
   * @return The dataId.
   */
  @java.lang.Override
  public java.lang.String getDataId() {
    java.lang.Object ref = dataId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dataId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 算力的powerId
   * </pre>
   *
   * <code>string data_id = 5;</code>
   * @return The bytes for dataId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDataIdBytes() {
    java.lang.Object ref = dataId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dataId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATA_STATUS_FIELD_NUMBER = 6;
  private int dataStatus_;
  /**
   * <pre>
   * the status of data, N means normal, D means deleted.
   * </pre>
   *
   * <code>.api.protobuf.DataStatus data_status = 6;</code>
   * @return The enum numeric value on the wire for dataStatus.
   */
  @java.lang.Override public int getDataStatusValue() {
    return dataStatus_;
  }
  /**
   * <pre>
   * the status of data, N means normal, D means deleted.
   * </pre>
   *
   * <code>.api.protobuf.DataStatus data_status = 6;</code>
   * @return The dataStatus.
   */
  @java.lang.Override public com.platon.rosettanet.admin.grpc.service.DataStatus getDataStatus() {
    @SuppressWarnings("deprecation")
    com.platon.rosettanet.admin.grpc.service.DataStatus result = com.platon.rosettanet.admin.grpc.service.DataStatus.valueOf(dataStatus_);
    return result == null ? com.platon.rosettanet.admin.grpc.service.DataStatus.UNRECOGNIZED : result;
  }

  public static final int STATE_FIELD_NUMBER = 7;
  private int state_;
  /**
   * <pre>
   * resource status, eg: create/release/revoke
   * </pre>
   *
   * <code>.api.protobuf.PowerState state = 7;</code>
   * @return The enum numeric value on the wire for state.
   */
  @java.lang.Override public int getStateValue() {
    return state_;
  }
  /**
   * <pre>
   * resource status, eg: create/release/revoke
   * </pre>
   *
   * <code>.api.protobuf.PowerState state = 7;</code>
   * @return The state.
   */
  @java.lang.Override public com.platon.rosettanet.admin.grpc.service.PowerState getState() {
    @SuppressWarnings("deprecation")
    com.platon.rosettanet.admin.grpc.service.PowerState result = com.platon.rosettanet.admin.grpc.service.PowerState.valueOf(state_);
    return result == null ? com.platon.rosettanet.admin.grpc.service.PowerState.UNRECOGNIZED : result;
  }

  public static final int TOTAL_MEM_FIELD_NUMBER = 8;
  private long totalMem_;
  /**
   * <pre>
   * unit: byte
   * </pre>
   *
   * <code>uint64 total_mem = 8;</code>
   * @return The totalMem.
   */
  @java.lang.Override
  public long getTotalMem() {
    return totalMem_;
  }

  public static final int USED_MEM_FIELD_NUMBER = 9;
  private long usedMem_;
  /**
   * <pre>
   * unit: byte
   * </pre>
   *
   * <code>uint64 used_mem = 9;</code>
   * @return The usedMem.
   */
  @java.lang.Override
  public long getUsedMem() {
    return usedMem_;
  }

  public static final int TOTAL_PROCESSOR_FIELD_NUMBER = 10;
  private int totalProcessor_;
  /**
   * <pre>
   * number of cpu cores.
   * </pre>
   *
   * <code>uint32 total_processor = 10;</code>
   * @return The totalProcessor.
   */
  @java.lang.Override
  public int getTotalProcessor() {
    return totalProcessor_;
  }

  public static final int USED_PROCESSOR_FIELD_NUMBER = 11;
  private int usedProcessor_;
  /**
   * <pre>
   * 算力已使用内核数 (单位: 个)
   * </pre>
   *
   * <code>uint32 used_processor = 11;</code>
   * @return The usedProcessor.
   */
  @java.lang.Override
  public int getUsedProcessor() {
    return usedProcessor_;
  }

  public static final int TOTAL_BANDWIDTH_FIELD_NUMBER = 12;
  private long totalBandwidth_;
  /**
   * <pre>
   * unit: byte
   * </pre>
   *
   * <code>uint64 total_bandwidth = 12;</code>
   * @return The totalBandwidth.
   */
  @java.lang.Override
  public long getTotalBandwidth() {
    return totalBandwidth_;
  }

  public static final int USED_BANDWIDTH_FIELD_NUMBER = 13;
  private long usedBandwidth_;
  /**
   * <pre>
   * 算力已使用带宽数 (单位: bps)
   * </pre>
   *
   * <code>uint64 used_bandwidth = 13;</code>
   * @return The usedBandwidth.
   */
  @java.lang.Override
  public long getUsedBandwidth() {
    return usedBandwidth_;
  }

  public static final int TOTAL_DISK_FIELD_NUMBER = 14;
  private long totalDisk_;
  /**
   * <pre>
   * 算力总磁盘容量 (单位: byte)
   * </pre>
   *
   * <code>uint64 total_disk = 14;</code>
   * @return The totalDisk.
   */
  @java.lang.Override
  public long getTotalDisk() {
    return totalDisk_;
  }

  public static final int USED_DISK_FIELD_NUMBER = 15;
  private long usedDisk_;
  /**
   * <pre>
   * 算力已使用磁盘容量 (单位: byte)
   * </pre>
   *
   * <code>uint64 used_disk = 15;</code>
   * @return The usedDisk.
   */
  @java.lang.Override
  public long getUsedDisk() {
    return usedDisk_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdentityIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, identityId_);
    }
    if (!getNodeIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nodeId_);
    }
    if (!getNodeNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, nodeName_);
    }
    if (!getJobNodeIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, jobNodeId_);
    }
    if (!getDataIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, dataId_);
    }
    if (dataStatus_ != com.platon.rosettanet.admin.grpc.service.DataStatus.DataStatus_Unknown.getNumber()) {
      output.writeEnum(6, dataStatus_);
    }
    if (state_ != com.platon.rosettanet.admin.grpc.service.PowerState.PowerState_Unknown.getNumber()) {
      output.writeEnum(7, state_);
    }
    if (totalMem_ != 0L) {
      output.writeUInt64(8, totalMem_);
    }
    if (usedMem_ != 0L) {
      output.writeUInt64(9, usedMem_);
    }
    if (totalProcessor_ != 0) {
      output.writeUInt32(10, totalProcessor_);
    }
    if (usedProcessor_ != 0) {
      output.writeUInt32(11, usedProcessor_);
    }
    if (totalBandwidth_ != 0L) {
      output.writeUInt64(12, totalBandwidth_);
    }
    if (usedBandwidth_ != 0L) {
      output.writeUInt64(13, usedBandwidth_);
    }
    if (totalDisk_ != 0L) {
      output.writeUInt64(14, totalDisk_);
    }
    if (usedDisk_ != 0L) {
      output.writeUInt64(15, usedDisk_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdentityIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, identityId_);
    }
    if (!getNodeIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nodeId_);
    }
    if (!getNodeNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, nodeName_);
    }
    if (!getJobNodeIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, jobNodeId_);
    }
    if (!getDataIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, dataId_);
    }
    if (dataStatus_ != com.platon.rosettanet.admin.grpc.service.DataStatus.DataStatus_Unknown.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, dataStatus_);
    }
    if (state_ != com.platon.rosettanet.admin.grpc.service.PowerState.PowerState_Unknown.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(7, state_);
    }
    if (totalMem_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(8, totalMem_);
    }
    if (usedMem_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(9, usedMem_);
    }
    if (totalProcessor_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(10, totalProcessor_);
    }
    if (usedProcessor_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(11, usedProcessor_);
    }
    if (totalBandwidth_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(12, totalBandwidth_);
    }
    if (usedBandwidth_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(13, usedBandwidth_);
    }
    if (totalDisk_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(14, totalDisk_);
    }
    if (usedDisk_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(15, usedDisk_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.platon.rosettanet.admin.grpc.service.LocalResourcePB)) {
      return super.equals(obj);
    }
    com.platon.rosettanet.admin.grpc.service.LocalResourcePB other = (com.platon.rosettanet.admin.grpc.service.LocalResourcePB) obj;

    if (!getIdentityId()
        .equals(other.getIdentityId())) return false;
    if (!getNodeId()
        .equals(other.getNodeId())) return false;
    if (!getNodeName()
        .equals(other.getNodeName())) return false;
    if (!getJobNodeId()
        .equals(other.getJobNodeId())) return false;
    if (!getDataId()
        .equals(other.getDataId())) return false;
    if (dataStatus_ != other.dataStatus_) return false;
    if (state_ != other.state_) return false;
    if (getTotalMem()
        != other.getTotalMem()) return false;
    if (getUsedMem()
        != other.getUsedMem()) return false;
    if (getTotalProcessor()
        != other.getTotalProcessor()) return false;
    if (getUsedProcessor()
        != other.getUsedProcessor()) return false;
    if (getTotalBandwidth()
        != other.getTotalBandwidth()) return false;
    if (getUsedBandwidth()
        != other.getUsedBandwidth()) return false;
    if (getTotalDisk()
        != other.getTotalDisk()) return false;
    if (getUsedDisk()
        != other.getUsedDisk()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IDENTITY_ID_FIELD_NUMBER;
    hash = (53 * hash) + getIdentityId().hashCode();
    hash = (37 * hash) + NODE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getNodeId().hashCode();
    hash = (37 * hash) + NODE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getNodeName().hashCode();
    hash = (37 * hash) + JOB_NODE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getJobNodeId().hashCode();
    hash = (37 * hash) + DATA_ID_FIELD_NUMBER;
    hash = (53 * hash) + getDataId().hashCode();
    hash = (37 * hash) + DATA_STATUS_FIELD_NUMBER;
    hash = (53 * hash) + dataStatus_;
    hash = (37 * hash) + STATE_FIELD_NUMBER;
    hash = (53 * hash) + state_;
    hash = (37 * hash) + TOTAL_MEM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalMem());
    hash = (37 * hash) + USED_MEM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUsedMem());
    hash = (37 * hash) + TOTAL_PROCESSOR_FIELD_NUMBER;
    hash = (53 * hash) + getTotalProcessor();
    hash = (37 * hash) + USED_PROCESSOR_FIELD_NUMBER;
    hash = (53 * hash) + getUsedProcessor();
    hash = (37 * hash) + TOTAL_BANDWIDTH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalBandwidth());
    hash = (37 * hash) + USED_BANDWIDTH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUsedBandwidth());
    hash = (37 * hash) + TOTAL_DISK_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalDisk());
    hash = (37 * hash) + USED_DISK_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUsedDisk());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.platon.rosettanet.admin.grpc.service.LocalResourcePB parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.platon.rosettanet.admin.grpc.service.LocalResourcePB parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.platon.rosettanet.admin.grpc.service.LocalResourcePB parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.platon.rosettanet.admin.grpc.service.LocalResourcePB parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.platon.rosettanet.admin.grpc.service.LocalResourcePB parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.platon.rosettanet.admin.grpc.service.LocalResourcePB parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.platon.rosettanet.admin.grpc.service.LocalResourcePB parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.platon.rosettanet.admin.grpc.service.LocalResourcePB parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.platon.rosettanet.admin.grpc.service.LocalResourcePB parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.platon.rosettanet.admin.grpc.service.LocalResourcePB parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.platon.rosettanet.admin.grpc.service.LocalResourcePB parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.platon.rosettanet.admin.grpc.service.LocalResourcePB parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.platon.rosettanet.admin.grpc.service.LocalResourcePB prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 单个组织中的单台服务的算力信息
   * </pre>
   *
   * Protobuf type {@code types.LocalResourcePB}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:types.LocalResourcePB)
      com.platon.rosettanet.admin.grpc.service.LocalResourcePBOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.platon.rosettanet.admin.grpc.service.ResourceDataProto.internal_static_types_LocalResourcePB_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.platon.rosettanet.admin.grpc.service.ResourceDataProto.internal_static_types_LocalResourcePB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.platon.rosettanet.admin.grpc.service.LocalResourcePB.class, com.platon.rosettanet.admin.grpc.service.LocalResourcePB.Builder.class);
    }

    // Construct using com.platon.rosettanet.admin.grpc.service.LocalResourcePB.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      identityId_ = "";

      nodeId_ = "";

      nodeName_ = "";

      jobNodeId_ = "";

      dataId_ = "";

      dataStatus_ = 0;

      state_ = 0;

      totalMem_ = 0L;

      usedMem_ = 0L;

      totalProcessor_ = 0;

      usedProcessor_ = 0;

      totalBandwidth_ = 0L;

      usedBandwidth_ = 0L;

      totalDisk_ = 0L;

      usedDisk_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.platon.rosettanet.admin.grpc.service.ResourceDataProto.internal_static_types_LocalResourcePB_descriptor;
    }

    @java.lang.Override
    public com.platon.rosettanet.admin.grpc.service.LocalResourcePB getDefaultInstanceForType() {
      return com.platon.rosettanet.admin.grpc.service.LocalResourcePB.getDefaultInstance();
    }

    @java.lang.Override
    public com.platon.rosettanet.admin.grpc.service.LocalResourcePB build() {
      com.platon.rosettanet.admin.grpc.service.LocalResourcePB result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.platon.rosettanet.admin.grpc.service.LocalResourcePB buildPartial() {
      com.platon.rosettanet.admin.grpc.service.LocalResourcePB result = new com.platon.rosettanet.admin.grpc.service.LocalResourcePB(this);
      result.identityId_ = identityId_;
      result.nodeId_ = nodeId_;
      result.nodeName_ = nodeName_;
      result.jobNodeId_ = jobNodeId_;
      result.dataId_ = dataId_;
      result.dataStatus_ = dataStatus_;
      result.state_ = state_;
      result.totalMem_ = totalMem_;
      result.usedMem_ = usedMem_;
      result.totalProcessor_ = totalProcessor_;
      result.usedProcessor_ = usedProcessor_;
      result.totalBandwidth_ = totalBandwidth_;
      result.usedBandwidth_ = usedBandwidth_;
      result.totalDisk_ = totalDisk_;
      result.usedDisk_ = usedDisk_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.platon.rosettanet.admin.grpc.service.LocalResourcePB) {
        return mergeFrom((com.platon.rosettanet.admin.grpc.service.LocalResourcePB)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.platon.rosettanet.admin.grpc.service.LocalResourcePB other) {
      if (other == com.platon.rosettanet.admin.grpc.service.LocalResourcePB.getDefaultInstance()) return this;
      if (!other.getIdentityId().isEmpty()) {
        identityId_ = other.identityId_;
        onChanged();
      }
      if (!other.getNodeId().isEmpty()) {
        nodeId_ = other.nodeId_;
        onChanged();
      }
      if (!other.getNodeName().isEmpty()) {
        nodeName_ = other.nodeName_;
        onChanged();
      }
      if (!other.getJobNodeId().isEmpty()) {
        jobNodeId_ = other.jobNodeId_;
        onChanged();
      }
      if (!other.getDataId().isEmpty()) {
        dataId_ = other.dataId_;
        onChanged();
      }
      if (other.dataStatus_ != 0) {
        setDataStatusValue(other.getDataStatusValue());
      }
      if (other.state_ != 0) {
        setStateValue(other.getStateValue());
      }
      if (other.getTotalMem() != 0L) {
        setTotalMem(other.getTotalMem());
      }
      if (other.getUsedMem() != 0L) {
        setUsedMem(other.getUsedMem());
      }
      if (other.getTotalProcessor() != 0) {
        setTotalProcessor(other.getTotalProcessor());
      }
      if (other.getUsedProcessor() != 0) {
        setUsedProcessor(other.getUsedProcessor());
      }
      if (other.getTotalBandwidth() != 0L) {
        setTotalBandwidth(other.getTotalBandwidth());
      }
      if (other.getUsedBandwidth() != 0L) {
        setUsedBandwidth(other.getUsedBandwidth());
      }
      if (other.getTotalDisk() != 0L) {
        setTotalDisk(other.getTotalDisk());
      }
      if (other.getUsedDisk() != 0L) {
        setUsedDisk(other.getUsedDisk());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.platon.rosettanet.admin.grpc.service.LocalResourcePB parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.platon.rosettanet.admin.grpc.service.LocalResourcePB) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object identityId_ = "";
    /**
     * <pre>
     * 算力所属的组织的 身份标识
     * </pre>
     *
     * <code>string identity_id = 1;</code>
     * @return The identityId.
     */
    public java.lang.String getIdentityId() {
      java.lang.Object ref = identityId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        identityId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 算力所属的组织的 身份标识
     * </pre>
     *
     * <code>string identity_id = 1;</code>
     * @return The bytes for identityId.
     */
    public com.google.protobuf.ByteString
        getIdentityIdBytes() {
      java.lang.Object ref = identityId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        identityId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 算力所属的组织的 身份标识
     * </pre>
     *
     * <code>string identity_id = 1;</code>
     * @param value The identityId to set.
     * @return This builder for chaining.
     */
    public Builder setIdentityId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      identityId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 算力所属的组织的 身份标识
     * </pre>
     *
     * <code>string identity_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdentityId() {
      
      identityId_ = getDefaultInstance().getIdentityId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 算力所属的组织的 身份标识
     * </pre>
     *
     * <code>string identity_id = 1;</code>
     * @param value The bytes for identityId to set.
     * @return This builder for chaining.
     */
    public Builder setIdentityIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      identityId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object nodeId_ = "";
    /**
     * <pre>
     * 算力所属的组织的 p2p公钥
     * </pre>
     *
     * <code>string node_id = 2;</code>
     * @return The nodeId.
     */
    public java.lang.String getNodeId() {
      java.lang.Object ref = nodeId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nodeId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 算力所属的组织的 p2p公钥
     * </pre>
     *
     * <code>string node_id = 2;</code>
     * @return The bytes for nodeId.
     */
    public com.google.protobuf.ByteString
        getNodeIdBytes() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 算力所属的组织的 p2p公钥
     * </pre>
     *
     * <code>string node_id = 2;</code>
     * @param value The nodeId to set.
     * @return This builder for chaining.
     */
    public Builder setNodeId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nodeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 算力所属的组织的 p2p公钥
     * </pre>
     *
     * <code>string node_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNodeId() {
      
      nodeId_ = getDefaultInstance().getNodeId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 算力所属的组织的 p2p公钥
     * </pre>
     *
     * <code>string node_id = 2;</code>
     * @param value The bytes for nodeId to set.
     * @return This builder for chaining.
     */
    public Builder setNodeIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nodeId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object nodeName_ = "";
    /**
     * <pre>
     * 算力所属的组织的 组织名称
     * </pre>
     *
     * <code>string node_name = 3;</code>
     * @return The nodeName.
     */
    public java.lang.String getNodeName() {
      java.lang.Object ref = nodeName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nodeName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 算力所属的组织的 组织名称
     * </pre>
     *
     * <code>string node_name = 3;</code>
     * @return The bytes for nodeName.
     */
    public com.google.protobuf.ByteString
        getNodeNameBytes() {
      java.lang.Object ref = nodeName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 算力所属的组织的 组织名称
     * </pre>
     *
     * <code>string node_name = 3;</code>
     * @param value The nodeName to set.
     * @return This builder for chaining.
     */
    public Builder setNodeName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nodeName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 算力所属的组织的 组织名称
     * </pre>
     *
     * <code>string node_name = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearNodeName() {
      
      nodeName_ = getDefaultInstance().getNodeName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 算力所属的组织的 组织名称
     * </pre>
     *
     * <code>string node_name = 3;</code>
     * @param value The bytes for nodeName to set.
     * @return This builder for chaining.
     */
    public Builder setNodeNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nodeName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object jobNodeId_ = "";
    /**
     * <pre>
     * 算力对应的内部计算服务的jobNodeId
     * </pre>
     *
     * <code>string job_node_id = 4;</code>
     * @return The jobNodeId.
     */
    public java.lang.String getJobNodeId() {
      java.lang.Object ref = jobNodeId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jobNodeId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 算力对应的内部计算服务的jobNodeId
     * </pre>
     *
     * <code>string job_node_id = 4;</code>
     * @return The bytes for jobNodeId.
     */
    public com.google.protobuf.ByteString
        getJobNodeIdBytes() {
      java.lang.Object ref = jobNodeId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jobNodeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 算力对应的内部计算服务的jobNodeId
     * </pre>
     *
     * <code>string job_node_id = 4;</code>
     * @param value The jobNodeId to set.
     * @return This builder for chaining.
     */
    public Builder setJobNodeId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      jobNodeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 算力对应的内部计算服务的jobNodeId
     * </pre>
     *
     * <code>string job_node_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearJobNodeId() {
      
      jobNodeId_ = getDefaultInstance().getJobNodeId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 算力对应的内部计算服务的jobNodeId
     * </pre>
     *
     * <code>string job_node_id = 4;</code>
     * @param value The bytes for jobNodeId to set.
     * @return This builder for chaining.
     */
    public Builder setJobNodeIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      jobNodeId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object dataId_ = "";
    /**
     * <pre>
     * 算力的powerId
     * </pre>
     *
     * <code>string data_id = 5;</code>
     * @return The dataId.
     */
    public java.lang.String getDataId() {
      java.lang.Object ref = dataId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dataId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 算力的powerId
     * </pre>
     *
     * <code>string data_id = 5;</code>
     * @return The bytes for dataId.
     */
    public com.google.protobuf.ByteString
        getDataIdBytes() {
      java.lang.Object ref = dataId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 算力的powerId
     * </pre>
     *
     * <code>string data_id = 5;</code>
     * @param value The dataId to set.
     * @return This builder for chaining.
     */
    public Builder setDataId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dataId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 算力的powerId
     * </pre>
     *
     * <code>string data_id = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDataId() {
      
      dataId_ = getDefaultInstance().getDataId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 算力的powerId
     * </pre>
     *
     * <code>string data_id = 5;</code>
     * @param value The bytes for dataId to set.
     * @return This builder for chaining.
     */
    public Builder setDataIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dataId_ = value;
      onChanged();
      return this;
    }

    private int dataStatus_ = 0;
    /**
     * <pre>
     * the status of data, N means normal, D means deleted.
     * </pre>
     *
     * <code>.api.protobuf.DataStatus data_status = 6;</code>
     * @return The enum numeric value on the wire for dataStatus.
     */
    @java.lang.Override public int getDataStatusValue() {
      return dataStatus_;
    }
    /**
     * <pre>
     * the status of data, N means normal, D means deleted.
     * </pre>
     *
     * <code>.api.protobuf.DataStatus data_status = 6;</code>
     * @param value The enum numeric value on the wire for dataStatus to set.
     * @return This builder for chaining.
     */
    public Builder setDataStatusValue(int value) {
      
      dataStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the status of data, N means normal, D means deleted.
     * </pre>
     *
     * <code>.api.protobuf.DataStatus data_status = 6;</code>
     * @return The dataStatus.
     */
    @java.lang.Override
    public com.platon.rosettanet.admin.grpc.service.DataStatus getDataStatus() {
      @SuppressWarnings("deprecation")
      com.platon.rosettanet.admin.grpc.service.DataStatus result = com.platon.rosettanet.admin.grpc.service.DataStatus.valueOf(dataStatus_);
      return result == null ? com.platon.rosettanet.admin.grpc.service.DataStatus.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * the status of data, N means normal, D means deleted.
     * </pre>
     *
     * <code>.api.protobuf.DataStatus data_status = 6;</code>
     * @param value The dataStatus to set.
     * @return This builder for chaining.
     */
    public Builder setDataStatus(com.platon.rosettanet.admin.grpc.service.DataStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      dataStatus_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the status of data, N means normal, D means deleted.
     * </pre>
     *
     * <code>.api.protobuf.DataStatus data_status = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearDataStatus() {
      
      dataStatus_ = 0;
      onChanged();
      return this;
    }

    private int state_ = 0;
    /**
     * <pre>
     * resource status, eg: create/release/revoke
     * </pre>
     *
     * <code>.api.protobuf.PowerState state = 7;</code>
     * @return The enum numeric value on the wire for state.
     */
    @java.lang.Override public int getStateValue() {
      return state_;
    }
    /**
     * <pre>
     * resource status, eg: create/release/revoke
     * </pre>
     *
     * <code>.api.protobuf.PowerState state = 7;</code>
     * @param value The enum numeric value on the wire for state to set.
     * @return This builder for chaining.
     */
    public Builder setStateValue(int value) {
      
      state_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * resource status, eg: create/release/revoke
     * </pre>
     *
     * <code>.api.protobuf.PowerState state = 7;</code>
     * @return The state.
     */
    @java.lang.Override
    public com.platon.rosettanet.admin.grpc.service.PowerState getState() {
      @SuppressWarnings("deprecation")
      com.platon.rosettanet.admin.grpc.service.PowerState result = com.platon.rosettanet.admin.grpc.service.PowerState.valueOf(state_);
      return result == null ? com.platon.rosettanet.admin.grpc.service.PowerState.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * resource status, eg: create/release/revoke
     * </pre>
     *
     * <code>.api.protobuf.PowerState state = 7;</code>
     * @param value The state to set.
     * @return This builder for chaining.
     */
    public Builder setState(com.platon.rosettanet.admin.grpc.service.PowerState value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      state_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * resource status, eg: create/release/revoke
     * </pre>
     *
     * <code>.api.protobuf.PowerState state = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearState() {
      
      state_ = 0;
      onChanged();
      return this;
    }

    private long totalMem_ ;
    /**
     * <pre>
     * unit: byte
     * </pre>
     *
     * <code>uint64 total_mem = 8;</code>
     * @return The totalMem.
     */
    @java.lang.Override
    public long getTotalMem() {
      return totalMem_;
    }
    /**
     * <pre>
     * unit: byte
     * </pre>
     *
     * <code>uint64 total_mem = 8;</code>
     * @param value The totalMem to set.
     * @return This builder for chaining.
     */
    public Builder setTotalMem(long value) {
      
      totalMem_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unit: byte
     * </pre>
     *
     * <code>uint64 total_mem = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalMem() {
      
      totalMem_ = 0L;
      onChanged();
      return this;
    }

    private long usedMem_ ;
    /**
     * <pre>
     * unit: byte
     * </pre>
     *
     * <code>uint64 used_mem = 9;</code>
     * @return The usedMem.
     */
    @java.lang.Override
    public long getUsedMem() {
      return usedMem_;
    }
    /**
     * <pre>
     * unit: byte
     * </pre>
     *
     * <code>uint64 used_mem = 9;</code>
     * @param value The usedMem to set.
     * @return This builder for chaining.
     */
    public Builder setUsedMem(long value) {
      
      usedMem_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unit: byte
     * </pre>
     *
     * <code>uint64 used_mem = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearUsedMem() {
      
      usedMem_ = 0L;
      onChanged();
      return this;
    }

    private int totalProcessor_ ;
    /**
     * <pre>
     * number of cpu cores.
     * </pre>
     *
     * <code>uint32 total_processor = 10;</code>
     * @return The totalProcessor.
     */
    @java.lang.Override
    public int getTotalProcessor() {
      return totalProcessor_;
    }
    /**
     * <pre>
     * number of cpu cores.
     * </pre>
     *
     * <code>uint32 total_processor = 10;</code>
     * @param value The totalProcessor to set.
     * @return This builder for chaining.
     */
    public Builder setTotalProcessor(int value) {
      
      totalProcessor_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * number of cpu cores.
     * </pre>
     *
     * <code>uint32 total_processor = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalProcessor() {
      
      totalProcessor_ = 0;
      onChanged();
      return this;
    }

    private int usedProcessor_ ;
    /**
     * <pre>
     * 算力已使用内核数 (单位: 个)
     * </pre>
     *
     * <code>uint32 used_processor = 11;</code>
     * @return The usedProcessor.
     */
    @java.lang.Override
    public int getUsedProcessor() {
      return usedProcessor_;
    }
    /**
     * <pre>
     * 算力已使用内核数 (单位: 个)
     * </pre>
     *
     * <code>uint32 used_processor = 11;</code>
     * @param value The usedProcessor to set.
     * @return This builder for chaining.
     */
    public Builder setUsedProcessor(int value) {
      
      usedProcessor_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 算力已使用内核数 (单位: 个)
     * </pre>
     *
     * <code>uint32 used_processor = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearUsedProcessor() {
      
      usedProcessor_ = 0;
      onChanged();
      return this;
    }

    private long totalBandwidth_ ;
    /**
     * <pre>
     * unit: byte
     * </pre>
     *
     * <code>uint64 total_bandwidth = 12;</code>
     * @return The totalBandwidth.
     */
    @java.lang.Override
    public long getTotalBandwidth() {
      return totalBandwidth_;
    }
    /**
     * <pre>
     * unit: byte
     * </pre>
     *
     * <code>uint64 total_bandwidth = 12;</code>
     * @param value The totalBandwidth to set.
     * @return This builder for chaining.
     */
    public Builder setTotalBandwidth(long value) {
      
      totalBandwidth_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unit: byte
     * </pre>
     *
     * <code>uint64 total_bandwidth = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalBandwidth() {
      
      totalBandwidth_ = 0L;
      onChanged();
      return this;
    }

    private long usedBandwidth_ ;
    /**
     * <pre>
     * 算力已使用带宽数 (单位: bps)
     * </pre>
     *
     * <code>uint64 used_bandwidth = 13;</code>
     * @return The usedBandwidth.
     */
    @java.lang.Override
    public long getUsedBandwidth() {
      return usedBandwidth_;
    }
    /**
     * <pre>
     * 算力已使用带宽数 (单位: bps)
     * </pre>
     *
     * <code>uint64 used_bandwidth = 13;</code>
     * @param value The usedBandwidth to set.
     * @return This builder for chaining.
     */
    public Builder setUsedBandwidth(long value) {
      
      usedBandwidth_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 算力已使用带宽数 (单位: bps)
     * </pre>
     *
     * <code>uint64 used_bandwidth = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearUsedBandwidth() {
      
      usedBandwidth_ = 0L;
      onChanged();
      return this;
    }

    private long totalDisk_ ;
    /**
     * <pre>
     * 算力总磁盘容量 (单位: byte)
     * </pre>
     *
     * <code>uint64 total_disk = 14;</code>
     * @return The totalDisk.
     */
    @java.lang.Override
    public long getTotalDisk() {
      return totalDisk_;
    }
    /**
     * <pre>
     * 算力总磁盘容量 (单位: byte)
     * </pre>
     *
     * <code>uint64 total_disk = 14;</code>
     * @param value The totalDisk to set.
     * @return This builder for chaining.
     */
    public Builder setTotalDisk(long value) {
      
      totalDisk_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 算力总磁盘容量 (单位: byte)
     * </pre>
     *
     * <code>uint64 total_disk = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalDisk() {
      
      totalDisk_ = 0L;
      onChanged();
      return this;
    }

    private long usedDisk_ ;
    /**
     * <pre>
     * 算力已使用磁盘容量 (单位: byte)
     * </pre>
     *
     * <code>uint64 used_disk = 15;</code>
     * @return The usedDisk.
     */
    @java.lang.Override
    public long getUsedDisk() {
      return usedDisk_;
    }
    /**
     * <pre>
     * 算力已使用磁盘容量 (单位: byte)
     * </pre>
     *
     * <code>uint64 used_disk = 15;</code>
     * @param value The usedDisk to set.
     * @return This builder for chaining.
     */
    public Builder setUsedDisk(long value) {
      
      usedDisk_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 算力已使用磁盘容量 (单位: byte)
     * </pre>
     *
     * <code>uint64 used_disk = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearUsedDisk() {
      
      usedDisk_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:types.LocalResourcePB)
  }

  // @@protoc_insertion_point(class_scope:types.LocalResourcePB)
  private static final com.platon.rosettanet.admin.grpc.service.LocalResourcePB DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.platon.rosettanet.admin.grpc.service.LocalResourcePB();
  }

  public static com.platon.rosettanet.admin.grpc.service.LocalResourcePB getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LocalResourcePB>
      PARSER = new com.google.protobuf.AbstractParser<LocalResourcePB>() {
    @java.lang.Override
    public LocalResourcePB parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LocalResourcePB(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LocalResourcePB> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LocalResourcePB> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.platon.rosettanet.admin.grpc.service.LocalResourcePB getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

