// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lib/types/metadata.proto

package com.platon.rosettanet.admin.grpc.service;

/**
 * <pre>
 * 元数据的详情信息
 * </pre>
 *
 * Protobuf type {@code types.MetadataDetail}
 */
public final class MetadataDetail extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:types.MetadataDetail)
    MetadataDetailOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MetadataDetail.newBuilder() to construct.
  private MetadataDetail(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MetadataDetail() {
    metadataColumns_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MetadataDetail();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MetadataDetail(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.platon.rosettanet.admin.grpc.service.MetadataSummary.Builder subBuilder = null;
            if (metadataSummary_ != null) {
              subBuilder = metadataSummary_.toBuilder();
            }
            metadataSummary_ = input.readMessage(com.platon.rosettanet.admin.grpc.service.MetadataSummary.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(metadataSummary_);
              metadataSummary_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              metadataColumns_ = new java.util.ArrayList<com.platon.rosettanet.admin.grpc.service.MetadataColumn>();
              mutable_bitField0_ |= 0x00000001;
            }
            metadataColumns_.add(
                input.readMessage(com.platon.rosettanet.admin.grpc.service.MetadataColumn.parser(), extensionRegistry));
            break;
          }
          case 24: {

            totalTaskCount_ = input.readUInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        metadataColumns_ = java.util.Collections.unmodifiableList(metadataColumns_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.platon.rosettanet.admin.grpc.service.MetaDataProto.internal_static_types_MetadataDetail_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.platon.rosettanet.admin.grpc.service.MetaDataProto.internal_static_types_MetadataDetail_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.platon.rosettanet.admin.grpc.service.MetadataDetail.class, com.platon.rosettanet.admin.grpc.service.MetadataDetail.Builder.class);
  }

  public static final int METADATA_SUMMARY_FIELD_NUMBER = 1;
  private com.platon.rosettanet.admin.grpc.service.MetadataSummary metadataSummary_;
  /**
   * <pre>
   * 元数据摘要
   * </pre>
   *
   * <code>.types.MetadataSummary metadata_summary = 1;</code>
   * @return Whether the metadataSummary field is set.
   */
  @java.lang.Override
  public boolean hasMetadataSummary() {
    return metadataSummary_ != null;
  }
  /**
   * <pre>
   * 元数据摘要
   * </pre>
   *
   * <code>.types.MetadataSummary metadata_summary = 1;</code>
   * @return The metadataSummary.
   */
  @java.lang.Override
  public com.platon.rosettanet.admin.grpc.service.MetadataSummary getMetadataSummary() {
    return metadataSummary_ == null ? com.platon.rosettanet.admin.grpc.service.MetadataSummary.getDefaultInstance() : metadataSummary_;
  }
  /**
   * <pre>
   * 元数据摘要
   * </pre>
   *
   * <code>.types.MetadataSummary metadata_summary = 1;</code>
   */
  @java.lang.Override
  public com.platon.rosettanet.admin.grpc.service.MetadataSummaryOrBuilder getMetadataSummaryOrBuilder() {
    return getMetadataSummary();
  }

  public static final int METADATA_COLUMNS_FIELD_NUMBER = 2;
  private java.util.List<com.platon.rosettanet.admin.grpc.service.MetadataColumn> metadataColumns_;
  /**
   * <pre>
   * 元数据对应原始文件对外暴露的列描述列表
   * </pre>
   *
   * <code>repeated .types.MetadataColumn metadata_columns = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.platon.rosettanet.admin.grpc.service.MetadataColumn> getMetadataColumnsList() {
    return metadataColumns_;
  }
  /**
   * <pre>
   * 元数据对应原始文件对外暴露的列描述列表
   * </pre>
   *
   * <code>repeated .types.MetadataColumn metadata_columns = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.platon.rosettanet.admin.grpc.service.MetadataColumnOrBuilder> 
      getMetadataColumnsOrBuilderList() {
    return metadataColumns_;
  }
  /**
   * <pre>
   * 元数据对应原始文件对外暴露的列描述列表
   * </pre>
   *
   * <code>repeated .types.MetadataColumn metadata_columns = 2;</code>
   */
  @java.lang.Override
  public int getMetadataColumnsCount() {
    return metadataColumns_.size();
  }
  /**
   * <pre>
   * 元数据对应原始文件对外暴露的列描述列表
   * </pre>
   *
   * <code>repeated .types.MetadataColumn metadata_columns = 2;</code>
   */
  @java.lang.Override
  public com.platon.rosettanet.admin.grpc.service.MetadataColumn getMetadataColumns(int index) {
    return metadataColumns_.get(index);
  }
  /**
   * <pre>
   * 元数据对应原始文件对外暴露的列描述列表
   * </pre>
   *
   * <code>repeated .types.MetadataColumn metadata_columns = 2;</code>
   */
  @java.lang.Override
  public com.platon.rosettanet.admin.grpc.service.MetadataColumnOrBuilder getMetadataColumnsOrBuilder(
      int index) {
    return metadataColumns_.get(index);
  }

  public static final int TOTAL_TASK_COUNT_FIELD_NUMBER = 3;
  private int totalTaskCount_;
  /**
   * <pre>
   * 该元数据参与过得任务数 (已完成的和正在执行的)
   * </pre>
   *
   * <code>uint32 total_task_count = 3;</code>
   * @return The totalTaskCount.
   */
  @java.lang.Override
  public int getTotalTaskCount() {
    return totalTaskCount_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (metadataSummary_ != null) {
      output.writeMessage(1, getMetadataSummary());
    }
    for (int i = 0; i < metadataColumns_.size(); i++) {
      output.writeMessage(2, metadataColumns_.get(i));
    }
    if (totalTaskCount_ != 0) {
      output.writeUInt32(3, totalTaskCount_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (metadataSummary_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getMetadataSummary());
    }
    for (int i = 0; i < metadataColumns_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, metadataColumns_.get(i));
    }
    if (totalTaskCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, totalTaskCount_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.platon.rosettanet.admin.grpc.service.MetadataDetail)) {
      return super.equals(obj);
    }
    com.platon.rosettanet.admin.grpc.service.MetadataDetail other = (com.platon.rosettanet.admin.grpc.service.MetadataDetail) obj;

    if (hasMetadataSummary() != other.hasMetadataSummary()) return false;
    if (hasMetadataSummary()) {
      if (!getMetadataSummary()
          .equals(other.getMetadataSummary())) return false;
    }
    if (!getMetadataColumnsList()
        .equals(other.getMetadataColumnsList())) return false;
    if (getTotalTaskCount()
        != other.getTotalTaskCount()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasMetadataSummary()) {
      hash = (37 * hash) + METADATA_SUMMARY_FIELD_NUMBER;
      hash = (53 * hash) + getMetadataSummary().hashCode();
    }
    if (getMetadataColumnsCount() > 0) {
      hash = (37 * hash) + METADATA_COLUMNS_FIELD_NUMBER;
      hash = (53 * hash) + getMetadataColumnsList().hashCode();
    }
    hash = (37 * hash) + TOTAL_TASK_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getTotalTaskCount();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.platon.rosettanet.admin.grpc.service.MetadataDetail parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.platon.rosettanet.admin.grpc.service.MetadataDetail parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.platon.rosettanet.admin.grpc.service.MetadataDetail parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.platon.rosettanet.admin.grpc.service.MetadataDetail parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.platon.rosettanet.admin.grpc.service.MetadataDetail parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.platon.rosettanet.admin.grpc.service.MetadataDetail parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.platon.rosettanet.admin.grpc.service.MetadataDetail parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.platon.rosettanet.admin.grpc.service.MetadataDetail parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.platon.rosettanet.admin.grpc.service.MetadataDetail parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.platon.rosettanet.admin.grpc.service.MetadataDetail parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.platon.rosettanet.admin.grpc.service.MetadataDetail parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.platon.rosettanet.admin.grpc.service.MetadataDetail parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.platon.rosettanet.admin.grpc.service.MetadataDetail prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 元数据的详情信息
   * </pre>
   *
   * Protobuf type {@code types.MetadataDetail}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:types.MetadataDetail)
      com.platon.rosettanet.admin.grpc.service.MetadataDetailOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.platon.rosettanet.admin.grpc.service.MetaDataProto.internal_static_types_MetadataDetail_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.platon.rosettanet.admin.grpc.service.MetaDataProto.internal_static_types_MetadataDetail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.platon.rosettanet.admin.grpc.service.MetadataDetail.class, com.platon.rosettanet.admin.grpc.service.MetadataDetail.Builder.class);
    }

    // Construct using com.platon.rosettanet.admin.grpc.service.MetadataDetail.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMetadataColumnsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (metadataSummaryBuilder_ == null) {
        metadataSummary_ = null;
      } else {
        metadataSummary_ = null;
        metadataSummaryBuilder_ = null;
      }
      if (metadataColumnsBuilder_ == null) {
        metadataColumns_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        metadataColumnsBuilder_.clear();
      }
      totalTaskCount_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.platon.rosettanet.admin.grpc.service.MetaDataProto.internal_static_types_MetadataDetail_descriptor;
    }

    @java.lang.Override
    public com.platon.rosettanet.admin.grpc.service.MetadataDetail getDefaultInstanceForType() {
      return com.platon.rosettanet.admin.grpc.service.MetadataDetail.getDefaultInstance();
    }

    @java.lang.Override
    public com.platon.rosettanet.admin.grpc.service.MetadataDetail build() {
      com.platon.rosettanet.admin.grpc.service.MetadataDetail result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.platon.rosettanet.admin.grpc.service.MetadataDetail buildPartial() {
      com.platon.rosettanet.admin.grpc.service.MetadataDetail result = new com.platon.rosettanet.admin.grpc.service.MetadataDetail(this);
      int from_bitField0_ = bitField0_;
      if (metadataSummaryBuilder_ == null) {
        result.metadataSummary_ = metadataSummary_;
      } else {
        result.metadataSummary_ = metadataSummaryBuilder_.build();
      }
      if (metadataColumnsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          metadataColumns_ = java.util.Collections.unmodifiableList(metadataColumns_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.metadataColumns_ = metadataColumns_;
      } else {
        result.metadataColumns_ = metadataColumnsBuilder_.build();
      }
      result.totalTaskCount_ = totalTaskCount_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.platon.rosettanet.admin.grpc.service.MetadataDetail) {
        return mergeFrom((com.platon.rosettanet.admin.grpc.service.MetadataDetail)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.platon.rosettanet.admin.grpc.service.MetadataDetail other) {
      if (other == com.platon.rosettanet.admin.grpc.service.MetadataDetail.getDefaultInstance()) return this;
      if (other.hasMetadataSummary()) {
        mergeMetadataSummary(other.getMetadataSummary());
      }
      if (metadataColumnsBuilder_ == null) {
        if (!other.metadataColumns_.isEmpty()) {
          if (metadataColumns_.isEmpty()) {
            metadataColumns_ = other.metadataColumns_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMetadataColumnsIsMutable();
            metadataColumns_.addAll(other.metadataColumns_);
          }
          onChanged();
        }
      } else {
        if (!other.metadataColumns_.isEmpty()) {
          if (metadataColumnsBuilder_.isEmpty()) {
            metadataColumnsBuilder_.dispose();
            metadataColumnsBuilder_ = null;
            metadataColumns_ = other.metadataColumns_;
            bitField0_ = (bitField0_ & ~0x00000001);
            metadataColumnsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMetadataColumnsFieldBuilder() : null;
          } else {
            metadataColumnsBuilder_.addAllMessages(other.metadataColumns_);
          }
        }
      }
      if (other.getTotalTaskCount() != 0) {
        setTotalTaskCount(other.getTotalTaskCount());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.platon.rosettanet.admin.grpc.service.MetadataDetail parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.platon.rosettanet.admin.grpc.service.MetadataDetail) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.platon.rosettanet.admin.grpc.service.MetadataSummary metadataSummary_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.platon.rosettanet.admin.grpc.service.MetadataSummary, com.platon.rosettanet.admin.grpc.service.MetadataSummary.Builder, com.platon.rosettanet.admin.grpc.service.MetadataSummaryOrBuilder> metadataSummaryBuilder_;
    /**
     * <pre>
     * 元数据摘要
     * </pre>
     *
     * <code>.types.MetadataSummary metadata_summary = 1;</code>
     * @return Whether the metadataSummary field is set.
     */
    public boolean hasMetadataSummary() {
      return metadataSummaryBuilder_ != null || metadataSummary_ != null;
    }
    /**
     * <pre>
     * 元数据摘要
     * </pre>
     *
     * <code>.types.MetadataSummary metadata_summary = 1;</code>
     * @return The metadataSummary.
     */
    public com.platon.rosettanet.admin.grpc.service.MetadataSummary getMetadataSummary() {
      if (metadataSummaryBuilder_ == null) {
        return metadataSummary_ == null ? com.platon.rosettanet.admin.grpc.service.MetadataSummary.getDefaultInstance() : metadataSummary_;
      } else {
        return metadataSummaryBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 元数据摘要
     * </pre>
     *
     * <code>.types.MetadataSummary metadata_summary = 1;</code>
     */
    public Builder setMetadataSummary(com.platon.rosettanet.admin.grpc.service.MetadataSummary value) {
      if (metadataSummaryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        metadataSummary_ = value;
        onChanged();
      } else {
        metadataSummaryBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 元数据摘要
     * </pre>
     *
     * <code>.types.MetadataSummary metadata_summary = 1;</code>
     */
    public Builder setMetadataSummary(
        com.platon.rosettanet.admin.grpc.service.MetadataSummary.Builder builderForValue) {
      if (metadataSummaryBuilder_ == null) {
        metadataSummary_ = builderForValue.build();
        onChanged();
      } else {
        metadataSummaryBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 元数据摘要
     * </pre>
     *
     * <code>.types.MetadataSummary metadata_summary = 1;</code>
     */
    public Builder mergeMetadataSummary(com.platon.rosettanet.admin.grpc.service.MetadataSummary value) {
      if (metadataSummaryBuilder_ == null) {
        if (metadataSummary_ != null) {
          metadataSummary_ =
            com.platon.rosettanet.admin.grpc.service.MetadataSummary.newBuilder(metadataSummary_).mergeFrom(value).buildPartial();
        } else {
          metadataSummary_ = value;
        }
        onChanged();
      } else {
        metadataSummaryBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 元数据摘要
     * </pre>
     *
     * <code>.types.MetadataSummary metadata_summary = 1;</code>
     */
    public Builder clearMetadataSummary() {
      if (metadataSummaryBuilder_ == null) {
        metadataSummary_ = null;
        onChanged();
      } else {
        metadataSummary_ = null;
        metadataSummaryBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 元数据摘要
     * </pre>
     *
     * <code>.types.MetadataSummary metadata_summary = 1;</code>
     */
    public com.platon.rosettanet.admin.grpc.service.MetadataSummary.Builder getMetadataSummaryBuilder() {
      
      onChanged();
      return getMetadataSummaryFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 元数据摘要
     * </pre>
     *
     * <code>.types.MetadataSummary metadata_summary = 1;</code>
     */
    public com.platon.rosettanet.admin.grpc.service.MetadataSummaryOrBuilder getMetadataSummaryOrBuilder() {
      if (metadataSummaryBuilder_ != null) {
        return metadataSummaryBuilder_.getMessageOrBuilder();
      } else {
        return metadataSummary_ == null ?
            com.platon.rosettanet.admin.grpc.service.MetadataSummary.getDefaultInstance() : metadataSummary_;
      }
    }
    /**
     * <pre>
     * 元数据摘要
     * </pre>
     *
     * <code>.types.MetadataSummary metadata_summary = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.platon.rosettanet.admin.grpc.service.MetadataSummary, com.platon.rosettanet.admin.grpc.service.MetadataSummary.Builder, com.platon.rosettanet.admin.grpc.service.MetadataSummaryOrBuilder> 
        getMetadataSummaryFieldBuilder() {
      if (metadataSummaryBuilder_ == null) {
        metadataSummaryBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.platon.rosettanet.admin.grpc.service.MetadataSummary, com.platon.rosettanet.admin.grpc.service.MetadataSummary.Builder, com.platon.rosettanet.admin.grpc.service.MetadataSummaryOrBuilder>(
                getMetadataSummary(),
                getParentForChildren(),
                isClean());
        metadataSummary_ = null;
      }
      return metadataSummaryBuilder_;
    }

    private java.util.List<com.platon.rosettanet.admin.grpc.service.MetadataColumn> metadataColumns_ =
      java.util.Collections.emptyList();
    private void ensureMetadataColumnsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        metadataColumns_ = new java.util.ArrayList<com.platon.rosettanet.admin.grpc.service.MetadataColumn>(metadataColumns_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.platon.rosettanet.admin.grpc.service.MetadataColumn, com.platon.rosettanet.admin.grpc.service.MetadataColumn.Builder, com.platon.rosettanet.admin.grpc.service.MetadataColumnOrBuilder> metadataColumnsBuilder_;

    /**
     * <pre>
     * 元数据对应原始文件对外暴露的列描述列表
     * </pre>
     *
     * <code>repeated .types.MetadataColumn metadata_columns = 2;</code>
     */
    public java.util.List<com.platon.rosettanet.admin.grpc.service.MetadataColumn> getMetadataColumnsList() {
      if (metadataColumnsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(metadataColumns_);
      } else {
        return metadataColumnsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 元数据对应原始文件对外暴露的列描述列表
     * </pre>
     *
     * <code>repeated .types.MetadataColumn metadata_columns = 2;</code>
     */
    public int getMetadataColumnsCount() {
      if (metadataColumnsBuilder_ == null) {
        return metadataColumns_.size();
      } else {
        return metadataColumnsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 元数据对应原始文件对外暴露的列描述列表
     * </pre>
     *
     * <code>repeated .types.MetadataColumn metadata_columns = 2;</code>
     */
    public com.platon.rosettanet.admin.grpc.service.MetadataColumn getMetadataColumns(int index) {
      if (metadataColumnsBuilder_ == null) {
        return metadataColumns_.get(index);
      } else {
        return metadataColumnsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 元数据对应原始文件对外暴露的列描述列表
     * </pre>
     *
     * <code>repeated .types.MetadataColumn metadata_columns = 2;</code>
     */
    public Builder setMetadataColumns(
        int index, com.platon.rosettanet.admin.grpc.service.MetadataColumn value) {
      if (metadataColumnsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMetadataColumnsIsMutable();
        metadataColumns_.set(index, value);
        onChanged();
      } else {
        metadataColumnsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 元数据对应原始文件对外暴露的列描述列表
     * </pre>
     *
     * <code>repeated .types.MetadataColumn metadata_columns = 2;</code>
     */
    public Builder setMetadataColumns(
        int index, com.platon.rosettanet.admin.grpc.service.MetadataColumn.Builder builderForValue) {
      if (metadataColumnsBuilder_ == null) {
        ensureMetadataColumnsIsMutable();
        metadataColumns_.set(index, builderForValue.build());
        onChanged();
      } else {
        metadataColumnsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 元数据对应原始文件对外暴露的列描述列表
     * </pre>
     *
     * <code>repeated .types.MetadataColumn metadata_columns = 2;</code>
     */
    public Builder addMetadataColumns(com.platon.rosettanet.admin.grpc.service.MetadataColumn value) {
      if (metadataColumnsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMetadataColumnsIsMutable();
        metadataColumns_.add(value);
        onChanged();
      } else {
        metadataColumnsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 元数据对应原始文件对外暴露的列描述列表
     * </pre>
     *
     * <code>repeated .types.MetadataColumn metadata_columns = 2;</code>
     */
    public Builder addMetadataColumns(
        int index, com.platon.rosettanet.admin.grpc.service.MetadataColumn value) {
      if (metadataColumnsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMetadataColumnsIsMutable();
        metadataColumns_.add(index, value);
        onChanged();
      } else {
        metadataColumnsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 元数据对应原始文件对外暴露的列描述列表
     * </pre>
     *
     * <code>repeated .types.MetadataColumn metadata_columns = 2;</code>
     */
    public Builder addMetadataColumns(
        com.platon.rosettanet.admin.grpc.service.MetadataColumn.Builder builderForValue) {
      if (metadataColumnsBuilder_ == null) {
        ensureMetadataColumnsIsMutable();
        metadataColumns_.add(builderForValue.build());
        onChanged();
      } else {
        metadataColumnsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 元数据对应原始文件对外暴露的列描述列表
     * </pre>
     *
     * <code>repeated .types.MetadataColumn metadata_columns = 2;</code>
     */
    public Builder addMetadataColumns(
        int index, com.platon.rosettanet.admin.grpc.service.MetadataColumn.Builder builderForValue) {
      if (metadataColumnsBuilder_ == null) {
        ensureMetadataColumnsIsMutable();
        metadataColumns_.add(index, builderForValue.build());
        onChanged();
      } else {
        metadataColumnsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 元数据对应原始文件对外暴露的列描述列表
     * </pre>
     *
     * <code>repeated .types.MetadataColumn metadata_columns = 2;</code>
     */
    public Builder addAllMetadataColumns(
        java.lang.Iterable<? extends com.platon.rosettanet.admin.grpc.service.MetadataColumn> values) {
      if (metadataColumnsBuilder_ == null) {
        ensureMetadataColumnsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, metadataColumns_);
        onChanged();
      } else {
        metadataColumnsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 元数据对应原始文件对外暴露的列描述列表
     * </pre>
     *
     * <code>repeated .types.MetadataColumn metadata_columns = 2;</code>
     */
    public Builder clearMetadataColumns() {
      if (metadataColumnsBuilder_ == null) {
        metadataColumns_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        metadataColumnsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 元数据对应原始文件对外暴露的列描述列表
     * </pre>
     *
     * <code>repeated .types.MetadataColumn metadata_columns = 2;</code>
     */
    public Builder removeMetadataColumns(int index) {
      if (metadataColumnsBuilder_ == null) {
        ensureMetadataColumnsIsMutable();
        metadataColumns_.remove(index);
        onChanged();
      } else {
        metadataColumnsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 元数据对应原始文件对外暴露的列描述列表
     * </pre>
     *
     * <code>repeated .types.MetadataColumn metadata_columns = 2;</code>
     */
    public com.platon.rosettanet.admin.grpc.service.MetadataColumn.Builder getMetadataColumnsBuilder(
        int index) {
      return getMetadataColumnsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 元数据对应原始文件对外暴露的列描述列表
     * </pre>
     *
     * <code>repeated .types.MetadataColumn metadata_columns = 2;</code>
     */
    public com.platon.rosettanet.admin.grpc.service.MetadataColumnOrBuilder getMetadataColumnsOrBuilder(
        int index) {
      if (metadataColumnsBuilder_ == null) {
        return metadataColumns_.get(index);  } else {
        return metadataColumnsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 元数据对应原始文件对外暴露的列描述列表
     * </pre>
     *
     * <code>repeated .types.MetadataColumn metadata_columns = 2;</code>
     */
    public java.util.List<? extends com.platon.rosettanet.admin.grpc.service.MetadataColumnOrBuilder> 
         getMetadataColumnsOrBuilderList() {
      if (metadataColumnsBuilder_ != null) {
        return metadataColumnsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(metadataColumns_);
      }
    }
    /**
     * <pre>
     * 元数据对应原始文件对外暴露的列描述列表
     * </pre>
     *
     * <code>repeated .types.MetadataColumn metadata_columns = 2;</code>
     */
    public com.platon.rosettanet.admin.grpc.service.MetadataColumn.Builder addMetadataColumnsBuilder() {
      return getMetadataColumnsFieldBuilder().addBuilder(
          com.platon.rosettanet.admin.grpc.service.MetadataColumn.getDefaultInstance());
    }
    /**
     * <pre>
     * 元数据对应原始文件对外暴露的列描述列表
     * </pre>
     *
     * <code>repeated .types.MetadataColumn metadata_columns = 2;</code>
     */
    public com.platon.rosettanet.admin.grpc.service.MetadataColumn.Builder addMetadataColumnsBuilder(
        int index) {
      return getMetadataColumnsFieldBuilder().addBuilder(
          index, com.platon.rosettanet.admin.grpc.service.MetadataColumn.getDefaultInstance());
    }
    /**
     * <pre>
     * 元数据对应原始文件对外暴露的列描述列表
     * </pre>
     *
     * <code>repeated .types.MetadataColumn metadata_columns = 2;</code>
     */
    public java.util.List<com.platon.rosettanet.admin.grpc.service.MetadataColumn.Builder> 
         getMetadataColumnsBuilderList() {
      return getMetadataColumnsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.platon.rosettanet.admin.grpc.service.MetadataColumn, com.platon.rosettanet.admin.grpc.service.MetadataColumn.Builder, com.platon.rosettanet.admin.grpc.service.MetadataColumnOrBuilder> 
        getMetadataColumnsFieldBuilder() {
      if (metadataColumnsBuilder_ == null) {
        metadataColumnsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.platon.rosettanet.admin.grpc.service.MetadataColumn, com.platon.rosettanet.admin.grpc.service.MetadataColumn.Builder, com.platon.rosettanet.admin.grpc.service.MetadataColumnOrBuilder>(
                metadataColumns_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        metadataColumns_ = null;
      }
      return metadataColumnsBuilder_;
    }

    private int totalTaskCount_ ;
    /**
     * <pre>
     * 该元数据参与过得任务数 (已完成的和正在执行的)
     * </pre>
     *
     * <code>uint32 total_task_count = 3;</code>
     * @return The totalTaskCount.
     */
    @java.lang.Override
    public int getTotalTaskCount() {
      return totalTaskCount_;
    }
    /**
     * <pre>
     * 该元数据参与过得任务数 (已完成的和正在执行的)
     * </pre>
     *
     * <code>uint32 total_task_count = 3;</code>
     * @param value The totalTaskCount to set.
     * @return This builder for chaining.
     */
    public Builder setTotalTaskCount(int value) {
      
      totalTaskCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 该元数据参与过得任务数 (已完成的和正在执行的)
     * </pre>
     *
     * <code>uint32 total_task_count = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalTaskCount() {
      
      totalTaskCount_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:types.MetadataDetail)
  }

  // @@protoc_insertion_point(class_scope:types.MetadataDetail)
  private static final com.platon.rosettanet.admin.grpc.service.MetadataDetail DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.platon.rosettanet.admin.grpc.service.MetadataDetail();
  }

  public static com.platon.rosettanet.admin.grpc.service.MetadataDetail getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MetadataDetail>
      PARSER = new com.google.protobuf.AbstractParser<MetadataDetail>() {
    @java.lang.Override
    public MetadataDetail parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MetadataDetail(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MetadataDetail> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MetadataDetail> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.platon.rosettanet.admin.grpc.service.MetadataDetail getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

