// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lib/common/base.proto

package com.platon.rosettanet.admin.grpc.service;

/**
 * <pre>
 * 元数据的使用方式类型枚举
 * </pre>
 *
 * Protobuf enum {@code api.protobuf.MetadataUsageType}
 */
public enum MetadataUsageType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * 未定义类型
   * </pre>
   *
   * <code>Usage_Unknown = 0;</code>
   */
  Usage_Unknown(0),
  /**
   * <pre>
   * 依照时间段来使用
   * </pre>
   *
   * <code>Usage_Period = 1;</code>
   */
  Usage_Period(1),
  /**
   * <pre>
   * 依照次数来使用
   * </pre>
   *
   * <code>Usage_Times = 2;</code>
   */
  Usage_Times(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * 未定义类型
   * </pre>
   *
   * <code>Usage_Unknown = 0;</code>
   */
  public static final int Usage_Unknown_VALUE = 0;
  /**
   * <pre>
   * 依照时间段来使用
   * </pre>
   *
   * <code>Usage_Period = 1;</code>
   */
  public static final int Usage_Period_VALUE = 1;
  /**
   * <pre>
   * 依照次数来使用
   * </pre>
   *
   * <code>Usage_Times = 2;</code>
   */
  public static final int Usage_Times_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static MetadataUsageType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static MetadataUsageType forNumber(int value) {
    switch (value) {
      case 0: return Usage_Unknown;
      case 1: return Usage_Period;
      case 2: return Usage_Times;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MetadataUsageType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MetadataUsageType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MetadataUsageType>() {
          public MetadataUsageType findValueByNumber(int number) {
            return MetadataUsageType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.platon.rosettanet.admin.grpc.service.Base.getDescriptor().getEnumTypes().get(6);
  }

  private static final MetadataUsageType[] VALUES = values();

  public static MetadataUsageType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private MetadataUsageType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:api.protobuf.MetadataUsageType)
}

