// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lib/types/metadata.proto

package com.platon.rosettanet.admin.grpc.service;

/**
 * <pre>
 * 元数据使用授权
 * </pre>
 *
 * Protobuf type {@code types.MetadataAuthority}
 */
public final class MetadataAuthority extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:types.MetadataAuthority)
    MetadataAuthorityOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MetadataAuthority.newBuilder() to construct.
  private MetadataAuthority(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MetadataAuthority() {
    metadataId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MetadataAuthority();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MetadataAuthority(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.platon.rosettanet.admin.grpc.service.Organization.Builder subBuilder = null;
            if (owner_ != null) {
              subBuilder = owner_.toBuilder();
            }
            owner_ = input.readMessage(com.platon.rosettanet.admin.grpc.service.Organization.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(owner_);
              owner_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            metadataId_ = s;
            break;
          }
          case 26: {
            com.platon.rosettanet.admin.grpc.service.MetadataUsageRule.Builder subBuilder = null;
            if (usageRule_ != null) {
              subBuilder = usageRule_.toBuilder();
            }
            usageRule_ = input.readMessage(com.platon.rosettanet.admin.grpc.service.MetadataUsageRule.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(usageRule_);
              usageRule_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.platon.rosettanet.admin.grpc.service.MetaDataProto.internal_static_types_MetadataAuthority_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.platon.rosettanet.admin.grpc.service.MetaDataProto.internal_static_types_MetadataAuthority_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.platon.rosettanet.admin.grpc.service.MetadataAuthority.class, com.platon.rosettanet.admin.grpc.service.MetadataAuthority.Builder.class);
  }

  public static final int OWNER_FIELD_NUMBER = 1;
  private com.platon.rosettanet.admin.grpc.service.Organization owner_;
  /**
   * <pre>
   * 元数据所属的组织信息
   * </pre>
   *
   * <code>.api.protobuf.Organization owner = 1;</code>
   * @return Whether the owner field is set.
   */
  @java.lang.Override
  public boolean hasOwner() {
    return owner_ != null;
  }
  /**
   * <pre>
   * 元数据所属的组织信息
   * </pre>
   *
   * <code>.api.protobuf.Organization owner = 1;</code>
   * @return The owner.
   */
  @java.lang.Override
  public com.platon.rosettanet.admin.grpc.service.Organization getOwner() {
    return owner_ == null ? com.platon.rosettanet.admin.grpc.service.Organization.getDefaultInstance() : owner_;
  }
  /**
   * <pre>
   * 元数据所属的组织信息
   * </pre>
   *
   * <code>.api.protobuf.Organization owner = 1;</code>
   */
  @java.lang.Override
  public com.platon.rosettanet.admin.grpc.service.OrganizationOrBuilder getOwnerOrBuilder() {
    return getOwner();
  }

  public static final int METADATA_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object metadataId_;
  /**
   * <pre>
   * 元数据Id
   * </pre>
   *
   * <code>string metadata_id = 2;</code>
   * @return The metadataId.
   */
  @java.lang.Override
  public java.lang.String getMetadataId() {
    java.lang.Object ref = metadataId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      metadataId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 元数据Id
   * </pre>
   *
   * <code>string metadata_id = 2;</code>
   * @return The bytes for metadataId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMetadataIdBytes() {
    java.lang.Object ref = metadataId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      metadataId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USAGE_RULE_FIELD_NUMBER = 3;
  private com.platon.rosettanet.admin.grpc.service.MetadataUsageRule usageRule_;
  /**
   * <pre>
   * 元数据怎么使用
   * </pre>
   *
   * <code>.types.MetadataUsageRule usage_rule = 3;</code>
   * @return Whether the usageRule field is set.
   */
  @java.lang.Override
  public boolean hasUsageRule() {
    return usageRule_ != null;
  }
  /**
   * <pre>
   * 元数据怎么使用
   * </pre>
   *
   * <code>.types.MetadataUsageRule usage_rule = 3;</code>
   * @return The usageRule.
   */
  @java.lang.Override
  public com.platon.rosettanet.admin.grpc.service.MetadataUsageRule getUsageRule() {
    return usageRule_ == null ? com.platon.rosettanet.admin.grpc.service.MetadataUsageRule.getDefaultInstance() : usageRule_;
  }
  /**
   * <pre>
   * 元数据怎么使用
   * </pre>
   *
   * <code>.types.MetadataUsageRule usage_rule = 3;</code>
   */
  @java.lang.Override
  public com.platon.rosettanet.admin.grpc.service.MetadataUsageRuleOrBuilder getUsageRuleOrBuilder() {
    return getUsageRule();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (owner_ != null) {
      output.writeMessage(1, getOwner());
    }
    if (!getMetadataIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, metadataId_);
    }
    if (usageRule_ != null) {
      output.writeMessage(3, getUsageRule());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (owner_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getOwner());
    }
    if (!getMetadataIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, metadataId_);
    }
    if (usageRule_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getUsageRule());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.platon.rosettanet.admin.grpc.service.MetadataAuthority)) {
      return super.equals(obj);
    }
    com.platon.rosettanet.admin.grpc.service.MetadataAuthority other = (com.platon.rosettanet.admin.grpc.service.MetadataAuthority) obj;

    if (hasOwner() != other.hasOwner()) return false;
    if (hasOwner()) {
      if (!getOwner()
          .equals(other.getOwner())) return false;
    }
    if (!getMetadataId()
        .equals(other.getMetadataId())) return false;
    if (hasUsageRule() != other.hasUsageRule()) return false;
    if (hasUsageRule()) {
      if (!getUsageRule()
          .equals(other.getUsageRule())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasOwner()) {
      hash = (37 * hash) + OWNER_FIELD_NUMBER;
      hash = (53 * hash) + getOwner().hashCode();
    }
    hash = (37 * hash) + METADATA_ID_FIELD_NUMBER;
    hash = (53 * hash) + getMetadataId().hashCode();
    if (hasUsageRule()) {
      hash = (37 * hash) + USAGE_RULE_FIELD_NUMBER;
      hash = (53 * hash) + getUsageRule().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.platon.rosettanet.admin.grpc.service.MetadataAuthority parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.platon.rosettanet.admin.grpc.service.MetadataAuthority parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.platon.rosettanet.admin.grpc.service.MetadataAuthority parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.platon.rosettanet.admin.grpc.service.MetadataAuthority parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.platon.rosettanet.admin.grpc.service.MetadataAuthority parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.platon.rosettanet.admin.grpc.service.MetadataAuthority parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.platon.rosettanet.admin.grpc.service.MetadataAuthority parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.platon.rosettanet.admin.grpc.service.MetadataAuthority parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.platon.rosettanet.admin.grpc.service.MetadataAuthority parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.platon.rosettanet.admin.grpc.service.MetadataAuthority parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.platon.rosettanet.admin.grpc.service.MetadataAuthority parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.platon.rosettanet.admin.grpc.service.MetadataAuthority parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.platon.rosettanet.admin.grpc.service.MetadataAuthority prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 元数据使用授权
   * </pre>
   *
   * Protobuf type {@code types.MetadataAuthority}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:types.MetadataAuthority)
      com.platon.rosettanet.admin.grpc.service.MetadataAuthorityOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.platon.rosettanet.admin.grpc.service.MetaDataProto.internal_static_types_MetadataAuthority_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.platon.rosettanet.admin.grpc.service.MetaDataProto.internal_static_types_MetadataAuthority_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.platon.rosettanet.admin.grpc.service.MetadataAuthority.class, com.platon.rosettanet.admin.grpc.service.MetadataAuthority.Builder.class);
    }

    // Construct using com.platon.rosettanet.admin.grpc.service.MetadataAuthority.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (ownerBuilder_ == null) {
        owner_ = null;
      } else {
        owner_ = null;
        ownerBuilder_ = null;
      }
      metadataId_ = "";

      if (usageRuleBuilder_ == null) {
        usageRule_ = null;
      } else {
        usageRule_ = null;
        usageRuleBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.platon.rosettanet.admin.grpc.service.MetaDataProto.internal_static_types_MetadataAuthority_descriptor;
    }

    @java.lang.Override
    public com.platon.rosettanet.admin.grpc.service.MetadataAuthority getDefaultInstanceForType() {
      return com.platon.rosettanet.admin.grpc.service.MetadataAuthority.getDefaultInstance();
    }

    @java.lang.Override
    public com.platon.rosettanet.admin.grpc.service.MetadataAuthority build() {
      com.platon.rosettanet.admin.grpc.service.MetadataAuthority result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.platon.rosettanet.admin.grpc.service.MetadataAuthority buildPartial() {
      com.platon.rosettanet.admin.grpc.service.MetadataAuthority result = new com.platon.rosettanet.admin.grpc.service.MetadataAuthority(this);
      if (ownerBuilder_ == null) {
        result.owner_ = owner_;
      } else {
        result.owner_ = ownerBuilder_.build();
      }
      result.metadataId_ = metadataId_;
      if (usageRuleBuilder_ == null) {
        result.usageRule_ = usageRule_;
      } else {
        result.usageRule_ = usageRuleBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.platon.rosettanet.admin.grpc.service.MetadataAuthority) {
        return mergeFrom((com.platon.rosettanet.admin.grpc.service.MetadataAuthority)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.platon.rosettanet.admin.grpc.service.MetadataAuthority other) {
      if (other == com.platon.rosettanet.admin.grpc.service.MetadataAuthority.getDefaultInstance()) return this;
      if (other.hasOwner()) {
        mergeOwner(other.getOwner());
      }
      if (!other.getMetadataId().isEmpty()) {
        metadataId_ = other.metadataId_;
        onChanged();
      }
      if (other.hasUsageRule()) {
        mergeUsageRule(other.getUsageRule());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.platon.rosettanet.admin.grpc.service.MetadataAuthority parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.platon.rosettanet.admin.grpc.service.MetadataAuthority) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.platon.rosettanet.admin.grpc.service.Organization owner_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.platon.rosettanet.admin.grpc.service.Organization, com.platon.rosettanet.admin.grpc.service.Organization.Builder, com.platon.rosettanet.admin.grpc.service.OrganizationOrBuilder> ownerBuilder_;
    /**
     * <pre>
     * 元数据所属的组织信息
     * </pre>
     *
     * <code>.api.protobuf.Organization owner = 1;</code>
     * @return Whether the owner field is set.
     */
    public boolean hasOwner() {
      return ownerBuilder_ != null || owner_ != null;
    }
    /**
     * <pre>
     * 元数据所属的组织信息
     * </pre>
     *
     * <code>.api.protobuf.Organization owner = 1;</code>
     * @return The owner.
     */
    public com.platon.rosettanet.admin.grpc.service.Organization getOwner() {
      if (ownerBuilder_ == null) {
        return owner_ == null ? com.platon.rosettanet.admin.grpc.service.Organization.getDefaultInstance() : owner_;
      } else {
        return ownerBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 元数据所属的组织信息
     * </pre>
     *
     * <code>.api.protobuf.Organization owner = 1;</code>
     */
    public Builder setOwner(com.platon.rosettanet.admin.grpc.service.Organization value) {
      if (ownerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        owner_ = value;
        onChanged();
      } else {
        ownerBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 元数据所属的组织信息
     * </pre>
     *
     * <code>.api.protobuf.Organization owner = 1;</code>
     */
    public Builder setOwner(
        com.platon.rosettanet.admin.grpc.service.Organization.Builder builderForValue) {
      if (ownerBuilder_ == null) {
        owner_ = builderForValue.build();
        onChanged();
      } else {
        ownerBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 元数据所属的组织信息
     * </pre>
     *
     * <code>.api.protobuf.Organization owner = 1;</code>
     */
    public Builder mergeOwner(com.platon.rosettanet.admin.grpc.service.Organization value) {
      if (ownerBuilder_ == null) {
        if (owner_ != null) {
          owner_ =
            com.platon.rosettanet.admin.grpc.service.Organization.newBuilder(owner_).mergeFrom(value).buildPartial();
        } else {
          owner_ = value;
        }
        onChanged();
      } else {
        ownerBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 元数据所属的组织信息
     * </pre>
     *
     * <code>.api.protobuf.Organization owner = 1;</code>
     */
    public Builder clearOwner() {
      if (ownerBuilder_ == null) {
        owner_ = null;
        onChanged();
      } else {
        owner_ = null;
        ownerBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 元数据所属的组织信息
     * </pre>
     *
     * <code>.api.protobuf.Organization owner = 1;</code>
     */
    public com.platon.rosettanet.admin.grpc.service.Organization.Builder getOwnerBuilder() {
      
      onChanged();
      return getOwnerFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 元数据所属的组织信息
     * </pre>
     *
     * <code>.api.protobuf.Organization owner = 1;</code>
     */
    public com.platon.rosettanet.admin.grpc.service.OrganizationOrBuilder getOwnerOrBuilder() {
      if (ownerBuilder_ != null) {
        return ownerBuilder_.getMessageOrBuilder();
      } else {
        return owner_ == null ?
            com.platon.rosettanet.admin.grpc.service.Organization.getDefaultInstance() : owner_;
      }
    }
    /**
     * <pre>
     * 元数据所属的组织信息
     * </pre>
     *
     * <code>.api.protobuf.Organization owner = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.platon.rosettanet.admin.grpc.service.Organization, com.platon.rosettanet.admin.grpc.service.Organization.Builder, com.platon.rosettanet.admin.grpc.service.OrganizationOrBuilder> 
        getOwnerFieldBuilder() {
      if (ownerBuilder_ == null) {
        ownerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.platon.rosettanet.admin.grpc.service.Organization, com.platon.rosettanet.admin.grpc.service.Organization.Builder, com.platon.rosettanet.admin.grpc.service.OrganizationOrBuilder>(
                getOwner(),
                getParentForChildren(),
                isClean());
        owner_ = null;
      }
      return ownerBuilder_;
    }

    private java.lang.Object metadataId_ = "";
    /**
     * <pre>
     * 元数据Id
     * </pre>
     *
     * <code>string metadata_id = 2;</code>
     * @return The metadataId.
     */
    public java.lang.String getMetadataId() {
      java.lang.Object ref = metadataId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        metadataId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 元数据Id
     * </pre>
     *
     * <code>string metadata_id = 2;</code>
     * @return The bytes for metadataId.
     */
    public com.google.protobuf.ByteString
        getMetadataIdBytes() {
      java.lang.Object ref = metadataId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        metadataId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 元数据Id
     * </pre>
     *
     * <code>string metadata_id = 2;</code>
     * @param value The metadataId to set.
     * @return This builder for chaining.
     */
    public Builder setMetadataId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      metadataId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 元数据Id
     * </pre>
     *
     * <code>string metadata_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMetadataId() {
      
      metadataId_ = getDefaultInstance().getMetadataId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 元数据Id
     * </pre>
     *
     * <code>string metadata_id = 2;</code>
     * @param value The bytes for metadataId to set.
     * @return This builder for chaining.
     */
    public Builder setMetadataIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      metadataId_ = value;
      onChanged();
      return this;
    }

    private com.platon.rosettanet.admin.grpc.service.MetadataUsageRule usageRule_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.platon.rosettanet.admin.grpc.service.MetadataUsageRule, com.platon.rosettanet.admin.grpc.service.MetadataUsageRule.Builder, com.platon.rosettanet.admin.grpc.service.MetadataUsageRuleOrBuilder> usageRuleBuilder_;
    /**
     * <pre>
     * 元数据怎么使用
     * </pre>
     *
     * <code>.types.MetadataUsageRule usage_rule = 3;</code>
     * @return Whether the usageRule field is set.
     */
    public boolean hasUsageRule() {
      return usageRuleBuilder_ != null || usageRule_ != null;
    }
    /**
     * <pre>
     * 元数据怎么使用
     * </pre>
     *
     * <code>.types.MetadataUsageRule usage_rule = 3;</code>
     * @return The usageRule.
     */
    public com.platon.rosettanet.admin.grpc.service.MetadataUsageRule getUsageRule() {
      if (usageRuleBuilder_ == null) {
        return usageRule_ == null ? com.platon.rosettanet.admin.grpc.service.MetadataUsageRule.getDefaultInstance() : usageRule_;
      } else {
        return usageRuleBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 元数据怎么使用
     * </pre>
     *
     * <code>.types.MetadataUsageRule usage_rule = 3;</code>
     */
    public Builder setUsageRule(com.platon.rosettanet.admin.grpc.service.MetadataUsageRule value) {
      if (usageRuleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        usageRule_ = value;
        onChanged();
      } else {
        usageRuleBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 元数据怎么使用
     * </pre>
     *
     * <code>.types.MetadataUsageRule usage_rule = 3;</code>
     */
    public Builder setUsageRule(
        com.platon.rosettanet.admin.grpc.service.MetadataUsageRule.Builder builderForValue) {
      if (usageRuleBuilder_ == null) {
        usageRule_ = builderForValue.build();
        onChanged();
      } else {
        usageRuleBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 元数据怎么使用
     * </pre>
     *
     * <code>.types.MetadataUsageRule usage_rule = 3;</code>
     */
    public Builder mergeUsageRule(com.platon.rosettanet.admin.grpc.service.MetadataUsageRule value) {
      if (usageRuleBuilder_ == null) {
        if (usageRule_ != null) {
          usageRule_ =
            com.platon.rosettanet.admin.grpc.service.MetadataUsageRule.newBuilder(usageRule_).mergeFrom(value).buildPartial();
        } else {
          usageRule_ = value;
        }
        onChanged();
      } else {
        usageRuleBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 元数据怎么使用
     * </pre>
     *
     * <code>.types.MetadataUsageRule usage_rule = 3;</code>
     */
    public Builder clearUsageRule() {
      if (usageRuleBuilder_ == null) {
        usageRule_ = null;
        onChanged();
      } else {
        usageRule_ = null;
        usageRuleBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 元数据怎么使用
     * </pre>
     *
     * <code>.types.MetadataUsageRule usage_rule = 3;</code>
     */
    public com.platon.rosettanet.admin.grpc.service.MetadataUsageRule.Builder getUsageRuleBuilder() {
      
      onChanged();
      return getUsageRuleFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 元数据怎么使用
     * </pre>
     *
     * <code>.types.MetadataUsageRule usage_rule = 3;</code>
     */
    public com.platon.rosettanet.admin.grpc.service.MetadataUsageRuleOrBuilder getUsageRuleOrBuilder() {
      if (usageRuleBuilder_ != null) {
        return usageRuleBuilder_.getMessageOrBuilder();
      } else {
        return usageRule_ == null ?
            com.platon.rosettanet.admin.grpc.service.MetadataUsageRule.getDefaultInstance() : usageRule_;
      }
    }
    /**
     * <pre>
     * 元数据怎么使用
     * </pre>
     *
     * <code>.types.MetadataUsageRule usage_rule = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.platon.rosettanet.admin.grpc.service.MetadataUsageRule, com.platon.rosettanet.admin.grpc.service.MetadataUsageRule.Builder, com.platon.rosettanet.admin.grpc.service.MetadataUsageRuleOrBuilder> 
        getUsageRuleFieldBuilder() {
      if (usageRuleBuilder_ == null) {
        usageRuleBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.platon.rosettanet.admin.grpc.service.MetadataUsageRule, com.platon.rosettanet.admin.grpc.service.MetadataUsageRule.Builder, com.platon.rosettanet.admin.grpc.service.MetadataUsageRuleOrBuilder>(
                getUsageRule(),
                getParentForChildren(),
                isClean());
        usageRule_ = null;
      }
      return usageRuleBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:types.MetadataAuthority)
  }

  // @@protoc_insertion_point(class_scope:types.MetadataAuthority)
  private static final com.platon.rosettanet.admin.grpc.service.MetadataAuthority DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.platon.rosettanet.admin.grpc.service.MetadataAuthority();
  }

  public static com.platon.rosettanet.admin.grpc.service.MetadataAuthority getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MetadataAuthority>
      PARSER = new com.google.protobuf.AbstractParser<MetadataAuthority>() {
    @java.lang.Override
    public MetadataAuthority parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MetadataAuthority(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MetadataAuthority> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MetadataAuthority> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.platon.rosettanet.admin.grpc.service.MetadataAuthority getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

