// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lib/common/base.proto

package com.platon.rosettanet.admin.grpc.service;

/**
 * <pre>
 * A represents the basic information of the organization.
 * </pre>
 *
 * Protobuf type {@code api.protobuf.Organization}
 */
public final class Organization extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:api.protobuf.Organization)
    OrganizationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Organization.newBuilder() to construct.
  private Organization(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Organization() {
    nodeName_ = "";
    nodeId_ = "";
    identityId_ = "";
    status_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Organization();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Organization(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            nodeName_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            nodeId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            identityId_ = s;
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.platon.rosettanet.admin.grpc.service.Base.internal_static_api_protobuf_Organization_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.platon.rosettanet.admin.grpc.service.Base.internal_static_api_protobuf_Organization_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.platon.rosettanet.admin.grpc.service.Organization.class, com.platon.rosettanet.admin.grpc.service.Organization.Builder.class);
  }

  public static final int NODE_NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object nodeName_;
  /**
   * <pre>
   * org name
   * </pre>
   *
   * <code>string node_name = 1;</code>
   * @return The nodeName.
   */
  @java.lang.Override
  public java.lang.String getNodeName() {
    java.lang.Object ref = nodeName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nodeName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * org name
   * </pre>
   *
   * <code>string node_name = 1;</code>
   * @return The bytes for nodeName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNodeNameBytes() {
    java.lang.Object ref = nodeName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nodeName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NODE_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object nodeId_;
  /**
   * <pre>
   * the node_id for org
   * </pre>
   *
   * <code>string node_id = 2;</code>
   * @return The nodeId.
   */
  @java.lang.Override
  public java.lang.String getNodeId() {
    java.lang.Object ref = nodeId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nodeId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * the node_id for org
   * </pre>
   *
   * <code>string node_id = 2;</code>
   * @return The bytes for nodeId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNodeIdBytes() {
    java.lang.Object ref = nodeId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nodeId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IDENTITY_ID_FIELD_NUMBER = 3;
  private volatile java.lang.Object identityId_;
  /**
   * <pre>
   * the identity for org
   * </pre>
   *
   * <code>string identity_id = 3;</code>
   * @return The identityId.
   */
  @java.lang.Override
  public java.lang.String getIdentityId() {
    java.lang.Object ref = identityId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      identityId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * the identity for org
   * </pre>
   *
   * <code>string identity_id = 3;</code>
   * @return The bytes for identityId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdentityIdBytes() {
    java.lang.Object ref = identityId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      identityId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 4;
  private int status_;
  /**
   * <pre>
   * the status for organization(deleted/normal)
   * </pre>
   *
   * <code>.api.protobuf.CommonStatus status = 4;</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override public int getStatusValue() {
    return status_;
  }
  /**
   * <pre>
   * the status for organization(deleted/normal)
   * </pre>
   *
   * <code>.api.protobuf.CommonStatus status = 4;</code>
   * @return The status.
   */
  @java.lang.Override public com.platon.rosettanet.admin.grpc.service.CommonStatus getStatus() {
    @SuppressWarnings("deprecation")
    com.platon.rosettanet.admin.grpc.service.CommonStatus result = com.platon.rosettanet.admin.grpc.service.CommonStatus.valueOf(status_);
    return result == null ? com.platon.rosettanet.admin.grpc.service.CommonStatus.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNodeNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nodeName_);
    }
    if (!getNodeIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nodeId_);
    }
    if (!getIdentityIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, identityId_);
    }
    if (status_ != com.platon.rosettanet.admin.grpc.service.CommonStatus.CommonStatus_Unknown.getNumber()) {
      output.writeEnum(4, status_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNodeNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nodeName_);
    }
    if (!getNodeIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nodeId_);
    }
    if (!getIdentityIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, identityId_);
    }
    if (status_ != com.platon.rosettanet.admin.grpc.service.CommonStatus.CommonStatus_Unknown.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, status_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.platon.rosettanet.admin.grpc.service.Organization)) {
      return super.equals(obj);
    }
    com.platon.rosettanet.admin.grpc.service.Organization other = (com.platon.rosettanet.admin.grpc.service.Organization) obj;

    if (!getNodeName()
        .equals(other.getNodeName())) return false;
    if (!getNodeId()
        .equals(other.getNodeId())) return false;
    if (!getIdentityId()
        .equals(other.getIdentityId())) return false;
    if (status_ != other.status_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NODE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getNodeName().hashCode();
    hash = (37 * hash) + NODE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getNodeId().hashCode();
    hash = (37 * hash) + IDENTITY_ID_FIELD_NUMBER;
    hash = (53 * hash) + getIdentityId().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.platon.rosettanet.admin.grpc.service.Organization parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.platon.rosettanet.admin.grpc.service.Organization parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.platon.rosettanet.admin.grpc.service.Organization parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.platon.rosettanet.admin.grpc.service.Organization parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.platon.rosettanet.admin.grpc.service.Organization parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.platon.rosettanet.admin.grpc.service.Organization parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.platon.rosettanet.admin.grpc.service.Organization parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.platon.rosettanet.admin.grpc.service.Organization parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.platon.rosettanet.admin.grpc.service.Organization parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.platon.rosettanet.admin.grpc.service.Organization parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.platon.rosettanet.admin.grpc.service.Organization parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.platon.rosettanet.admin.grpc.service.Organization parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.platon.rosettanet.admin.grpc.service.Organization prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A represents the basic information of the organization.
   * </pre>
   *
   * Protobuf type {@code api.protobuf.Organization}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.protobuf.Organization)
      com.platon.rosettanet.admin.grpc.service.OrganizationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.platon.rosettanet.admin.grpc.service.Base.internal_static_api_protobuf_Organization_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.platon.rosettanet.admin.grpc.service.Base.internal_static_api_protobuf_Organization_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.platon.rosettanet.admin.grpc.service.Organization.class, com.platon.rosettanet.admin.grpc.service.Organization.Builder.class);
    }

    // Construct using com.platon.rosettanet.admin.grpc.service.Organization.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      nodeName_ = "";

      nodeId_ = "";

      identityId_ = "";

      status_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.platon.rosettanet.admin.grpc.service.Base.internal_static_api_protobuf_Organization_descriptor;
    }

    @java.lang.Override
    public com.platon.rosettanet.admin.grpc.service.Organization getDefaultInstanceForType() {
      return com.platon.rosettanet.admin.grpc.service.Organization.getDefaultInstance();
    }

    @java.lang.Override
    public com.platon.rosettanet.admin.grpc.service.Organization build() {
      com.platon.rosettanet.admin.grpc.service.Organization result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.platon.rosettanet.admin.grpc.service.Organization buildPartial() {
      com.platon.rosettanet.admin.grpc.service.Organization result = new com.platon.rosettanet.admin.grpc.service.Organization(this);
      result.nodeName_ = nodeName_;
      result.nodeId_ = nodeId_;
      result.identityId_ = identityId_;
      result.status_ = status_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.platon.rosettanet.admin.grpc.service.Organization) {
        return mergeFrom((com.platon.rosettanet.admin.grpc.service.Organization)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.platon.rosettanet.admin.grpc.service.Organization other) {
      if (other == com.platon.rosettanet.admin.grpc.service.Organization.getDefaultInstance()) return this;
      if (!other.getNodeName().isEmpty()) {
        nodeName_ = other.nodeName_;
        onChanged();
      }
      if (!other.getNodeId().isEmpty()) {
        nodeId_ = other.nodeId_;
        onChanged();
      }
      if (!other.getIdentityId().isEmpty()) {
        identityId_ = other.identityId_;
        onChanged();
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.platon.rosettanet.admin.grpc.service.Organization parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.platon.rosettanet.admin.grpc.service.Organization) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object nodeName_ = "";
    /**
     * <pre>
     * org name
     * </pre>
     *
     * <code>string node_name = 1;</code>
     * @return The nodeName.
     */
    public java.lang.String getNodeName() {
      java.lang.Object ref = nodeName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nodeName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * org name
     * </pre>
     *
     * <code>string node_name = 1;</code>
     * @return The bytes for nodeName.
     */
    public com.google.protobuf.ByteString
        getNodeNameBytes() {
      java.lang.Object ref = nodeName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * org name
     * </pre>
     *
     * <code>string node_name = 1;</code>
     * @param value The nodeName to set.
     * @return This builder for chaining.
     */
    public Builder setNodeName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nodeName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * org name
     * </pre>
     *
     * <code>string node_name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNodeName() {
      
      nodeName_ = getDefaultInstance().getNodeName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * org name
     * </pre>
     *
     * <code>string node_name = 1;</code>
     * @param value The bytes for nodeName to set.
     * @return This builder for chaining.
     */
    public Builder setNodeNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nodeName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object nodeId_ = "";
    /**
     * <pre>
     * the node_id for org
     * </pre>
     *
     * <code>string node_id = 2;</code>
     * @return The nodeId.
     */
    public java.lang.String getNodeId() {
      java.lang.Object ref = nodeId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nodeId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * the node_id for org
     * </pre>
     *
     * <code>string node_id = 2;</code>
     * @return The bytes for nodeId.
     */
    public com.google.protobuf.ByteString
        getNodeIdBytes() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * the node_id for org
     * </pre>
     *
     * <code>string node_id = 2;</code>
     * @param value The nodeId to set.
     * @return This builder for chaining.
     */
    public Builder setNodeId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nodeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the node_id for org
     * </pre>
     *
     * <code>string node_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNodeId() {
      
      nodeId_ = getDefaultInstance().getNodeId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the node_id for org
     * </pre>
     *
     * <code>string node_id = 2;</code>
     * @param value The bytes for nodeId to set.
     * @return This builder for chaining.
     */
    public Builder setNodeIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nodeId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object identityId_ = "";
    /**
     * <pre>
     * the identity for org
     * </pre>
     *
     * <code>string identity_id = 3;</code>
     * @return The identityId.
     */
    public java.lang.String getIdentityId() {
      java.lang.Object ref = identityId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        identityId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * the identity for org
     * </pre>
     *
     * <code>string identity_id = 3;</code>
     * @return The bytes for identityId.
     */
    public com.google.protobuf.ByteString
        getIdentityIdBytes() {
      java.lang.Object ref = identityId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        identityId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * the identity for org
     * </pre>
     *
     * <code>string identity_id = 3;</code>
     * @param value The identityId to set.
     * @return This builder for chaining.
     */
    public Builder setIdentityId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      identityId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the identity for org
     * </pre>
     *
     * <code>string identity_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdentityId() {
      
      identityId_ = getDefaultInstance().getIdentityId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the identity for org
     * </pre>
     *
     * <code>string identity_id = 3;</code>
     * @param value The bytes for identityId to set.
     * @return This builder for chaining.
     */
    public Builder setIdentityIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      identityId_ = value;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <pre>
     * the status for organization(deleted/normal)
     * </pre>
     *
     * <code>.api.protobuf.CommonStatus status = 4;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <pre>
     * the status for organization(deleted/normal)
     * </pre>
     *
     * <code>.api.protobuf.CommonStatus status = 4;</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the status for organization(deleted/normal)
     * </pre>
     *
     * <code>.api.protobuf.CommonStatus status = 4;</code>
     * @return The status.
     */
    @java.lang.Override
    public com.platon.rosettanet.admin.grpc.service.CommonStatus getStatus() {
      @SuppressWarnings("deprecation")
      com.platon.rosettanet.admin.grpc.service.CommonStatus result = com.platon.rosettanet.admin.grpc.service.CommonStatus.valueOf(status_);
      return result == null ? com.platon.rosettanet.admin.grpc.service.CommonStatus.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * the status for organization(deleted/normal)
     * </pre>
     *
     * <code>.api.protobuf.CommonStatus status = 4;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(com.platon.rosettanet.admin.grpc.service.CommonStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the status for organization(deleted/normal)
     * </pre>
     *
     * <code>.api.protobuf.CommonStatus status = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:api.protobuf.Organization)
  }

  // @@protoc_insertion_point(class_scope:api.protobuf.Organization)
  private static final com.platon.rosettanet.admin.grpc.service.Organization DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.platon.rosettanet.admin.grpc.service.Organization();
  }

  public static com.platon.rosettanet.admin.grpc.service.Organization getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Organization>
      PARSER = new com.google.protobuf.AbstractParser<Organization>() {
    @java.lang.Override
    public Organization parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Organization(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Organization> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Organization> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.platon.rosettanet.admin.grpc.service.Organization getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

