// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lib/common/base.proto

package com.platon.rosettanet.admin.grpc.service;

/**
 * <pre>
 *原始文件类型
 * </pre>
 *
 * Protobuf enum {@code api.protobuf.OriginFileType}
 */
public enum OriginFileType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * 未知
   * </pre>
   *
   * <code>FileType_Unknown = 0;</code>
   */
  FileType_Unknown(0),
  /**
   * <pre>
   * csv, 目前只支持这个.
   * </pre>
   *
   * <code>FileType_CSV = 1;</code>
   */
  FileType_CSV(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * 未知
   * </pre>
   *
   * <code>FileType_Unknown = 0;</code>
   */
  public static final int FileType_Unknown_VALUE = 0;
  /**
   * <pre>
   * csv, 目前只支持这个.
   * </pre>
   *
   * <code>FileType_CSV = 1;</code>
   */
  public static final int FileType_CSV_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static OriginFileType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static OriginFileType forNumber(int value) {
    switch (value) {
      case 0: return FileType_Unknown;
      case 1: return FileType_CSV;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<OriginFileType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      OriginFileType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<OriginFileType>() {
          public OriginFileType findValueByNumber(int number) {
            return OriginFileType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.platon.rosettanet.admin.grpc.service.Base.getDescriptor().getEnumTypes().get(4);
  }

  private static final OriginFileType[] VALUES = values();

  public static OriginFileType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private OriginFileType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:api.protobuf.OriginFileType)
}

