// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lib/common/base.proto

package com.platon.rosettanet.admin.grpc.service;

/**
 * <pre>
 * 算力的状态 (0: 未知; 1: 还未发布的算力; 2: 已发布的算力; 3: 已撤销的算力)
 * </pre>
 *
 * Protobuf enum {@code api.protobuf.PowerState}
 */
public enum PowerState
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>PowerState_Unknown = 0;</code>
   */
  PowerState_Unknown(0),
  /**
   * <code>PowerState_Created = 1;</code>
   */
  PowerState_Created(1),
  /**
   * <code>PowerState_Released = 2;</code>
   */
  PowerState_Released(2),
  /**
   * <code>PowerState_Revoked = 3;</code>
   */
  PowerState_Revoked(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>PowerState_Unknown = 0;</code>
   */
  public static final int PowerState_Unknown_VALUE = 0;
  /**
   * <code>PowerState_Created = 1;</code>
   */
  public static final int PowerState_Created_VALUE = 1;
  /**
   * <code>PowerState_Released = 2;</code>
   */
  public static final int PowerState_Released_VALUE = 2;
  /**
   * <code>PowerState_Revoked = 3;</code>
   */
  public static final int PowerState_Revoked_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static PowerState valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static PowerState forNumber(int value) {
    switch (value) {
      case 0: return PowerState_Unknown;
      case 1: return PowerState_Created;
      case 2: return PowerState_Released;
      case 3: return PowerState_Revoked;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PowerState>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      PowerState> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PowerState>() {
          public PowerState findValueByNumber(int number) {
            return PowerState.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.platon.rosettanet.admin.grpc.service.Base.getDescriptor().getEnumTypes().get(7);
  }

  private static final PowerState[] VALUES = values();

  public static PowerState valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private PowerState(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:api.protobuf.PowerState)
}

