// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lib/types/resourcedata.proto

package com.platon.rosettanet.admin.grpc.service;

public interface PowerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:types.Power)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 计算服务id (节点内部的)
   * </pre>
   *
   * <code>string job_node_id = 1;</code>
   * @return The jobNodeId.
   */
  java.lang.String getJobNodeId();
  /**
   * <pre>
   * 计算服务id (节点内部的)
   * </pre>
   *
   * <code>string job_node_id = 1;</code>
   * @return The bytes for jobNodeId.
   */
  com.google.protobuf.ByteString
      getJobNodeIdBytes();

  /**
   * <pre>
   * 算力id
   * </pre>
   *
   * <code>string power_id = 2;</code>
   * @return The powerId.
   */
  java.lang.String getPowerId();
  /**
   * <pre>
   * 算力id
   * </pre>
   *
   * <code>string power_id = 2;</code>
   * @return The bytes for powerId.
   */
  com.google.protobuf.ByteString
      getPowerIdBytes();

  /**
   * <pre>
   * 算力实况
   * </pre>
   *
   * <code>.types.ResourceUsageOverview usage_overview = 3;</code>
   * @return Whether the usageOverview field is set.
   */
  boolean hasUsageOverview();
  /**
   * <pre>
   * 算力实况
   * </pre>
   *
   * <code>.types.ResourceUsageOverview usage_overview = 3;</code>
   * @return The usageOverview.
   */
  com.platon.rosettanet.admin.grpc.service.ResourceUsageOverview getUsageOverview();
  /**
   * <pre>
   * 算力实况
   * </pre>
   *
   * <code>.types.ResourceUsageOverview usage_overview = 3;</code>
   */
  com.platon.rosettanet.admin.grpc.service.ResourceUsageOverviewOrBuilder getUsageOverviewOrBuilder();

  /**
   * <pre>
   * 算力的状态 (0: 未知; 1: 还未发布的算力; 2: 已发布的算力; 3: 已撤销的算力)
   * </pre>
   *
   * <code>.api.protobuf.PowerState state = 4;</code>
   * @return The enum numeric value on the wire for state.
   */
  int getStateValue();
  /**
   * <pre>
   * 算力的状态 (0: 未知; 1: 还未发布的算力; 2: 已发布的算力; 3: 已撤销的算力)
   * </pre>
   *
   * <code>.api.protobuf.PowerState state = 4;</code>
   * @return The state.
   */
  com.platon.rosettanet.admin.grpc.service.PowerState getState();
}
