// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lib/types/resourcedata.proto

package com.platon.rosettanet.admin.grpc.service;

public interface ResourceUsageOverviewOrBuilder extends
    // @@protoc_insertion_point(interface_extends:types.ResourceUsageOverview)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 服务系统的总内存 (单位: byte)
   * </pre>
   *
   * <code>uint64 total_mem = 2;</code>
   * @return The totalMem.
   */
  long getTotalMem();

  /**
   * <pre>
   * 服务系统的已用内存  (单位: byte)
   * </pre>
   *
   * <code>uint64 used_mem = 3;</code>
   * @return The usedMem.
   */
  long getUsedMem();

  /**
   * <pre>
   * 服务的总内核数 (单位: 个)
   * </pre>
   *
   * <code>uint32 total_processor = 4;</code>
   * @return The totalProcessor.
   */
  int getTotalProcessor();

  /**
   * <pre>
   * 服务的已用内核数 (单位: 个)
   * </pre>
   *
   * <code>uint32 used_processor = 5;</code>
   * @return The usedProcessor.
   */
  int getUsedProcessor();

  /**
   * <pre>
   * 服务的总带宽数 (单位: bps)
   * </pre>
   *
   * <code>uint64 total_bandwidth = 6;</code>
   * @return The totalBandwidth.
   */
  long getTotalBandwidth();

  /**
   * <pre>
   * 服务的已用带宽数 (单位: bps)
   * </pre>
   *
   * <code>uint64 used_bandwidth = 7;</code>
   * @return The usedBandwidth.
   */
  long getUsedBandwidth();

  /**
   * <pre>
   * 服务的总磁盘空间 (单位: byte)
   * </pre>
   *
   * <code>uint64 total_disk = 8;</code>
   * @return The totalDisk.
   */
  long getTotalDisk();

  /**
   * <pre>
   * 服务的已用磁盘空间 (单位: byte)
   * </pre>
   *
   * <code>uint64 used_disk = 9;</code>
   * @return The usedDisk.
   */
  long getUsedDisk();
}
