// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lib/types/taskdata.proto

package com.platon.rosettanet.admin.grpc.service;

public interface TaskPBOrBuilder extends
    // @@protoc_insertion_point(interface_extends:types.TaskPB)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 任务发起方的 组织的 身份标识
   * </pre>
   *
   * <code>string identity_id = 1;</code>
   * @return The identityId.
   */
  java.lang.String getIdentityId();
  /**
   * <pre>
   * 任务发起方的 组织的 身份标识
   * </pre>
   *
   * <code>string identity_id = 1;</code>
   * @return The bytes for identityId.
   */
  com.google.protobuf.ByteString
      getIdentityIdBytes();

  /**
   * <pre>
   * 任务发起方的 组织的 p2p公钥
   * </pre>
   *
   * <code>string node_id = 2;</code>
   * @return The nodeId.
   */
  java.lang.String getNodeId();
  /**
   * <pre>
   * 任务发起方的 组织的 p2p公钥
   * </pre>
   *
   * <code>string node_id = 2;</code>
   * @return The bytes for nodeId.
   */
  com.google.protobuf.ByteString
      getNodeIdBytes();

  /**
   * <pre>
   * 任务发起方的 组织的名称
   * </pre>
   *
   * <code>string node_name = 3;</code>
   * @return The nodeName.
   */
  java.lang.String getNodeName();
  /**
   * <pre>
   * 任务发起方的 组织的名称
   * </pre>
   *
   * <code>string node_name = 3;</code>
   * @return The bytes for nodeName.
   */
  com.google.protobuf.ByteString
      getNodeNameBytes();

  /**
   * <pre>
   * </pre>
   *
   * <code>string data_id = 4;</code>
   * @return The dataId.
   */
  java.lang.String getDataId();
  /**
   * <pre>
   * </pre>
   *
   * <code>string data_id = 4;</code>
   * @return The bytes for dataId.
   */
  com.google.protobuf.ByteString
      getDataIdBytes();

  /**
   * <pre>
   * the status of data, N means normal, D means deleted.
   * </pre>
   *
   * <code>.api.protobuf.DataStatus data_status = 5;</code>
   * @return The enum numeric value on the wire for dataStatus.
   */
  int getDataStatusValue();
  /**
   * <pre>
   * the status of data, N means normal, D means deleted.
   * </pre>
   *
   * <code>.api.protobuf.DataStatus data_status = 5;</code>
   * @return The dataStatus.
   */
  com.platon.rosettanet.admin.grpc.service.DataStatus getDataStatus();

  /**
   * <pre>
   * 任务Id
   * </pre>
   *
   * <code>string task_id = 6;</code>
   * @return The taskId.
   */
  java.lang.String getTaskId();
  /**
   * <pre>
   * 任务Id
   * </pre>
   *
   * <code>string task_id = 6;</code>
   * @return The bytes for taskId.
   */
  com.google.protobuf.ByteString
      getTaskIdBytes();

  /**
   * <pre>
   * 任务名称
   * </pre>
   *
   * <code>string task_name = 7;</code>
   * @return The taskName.
   */
  java.lang.String getTaskName();
  /**
   * <pre>
   * 任务名称
   * </pre>
   *
   * <code>string task_name = 7;</code>
   * @return The bytes for taskName.
   */
  com.google.protobuf.ByteString
      getTaskNameBytes();

  /**
   * <pre>
   * 任务的状态 (0: 未知; 1: 等在中; 2: 计算中; 3: 失败; 4: 成功)
   * </pre>
   *
   * <code>.api.protobuf.TaskState state = 8;</code>
   * @return The enum numeric value on the wire for state.
   */
  int getStateValue();
  /**
   * <pre>
   * 任务的状态 (0: 未知; 1: 等在中; 2: 计算中; 3: 失败; 4: 成功)
   * </pre>
   *
   * <code>.api.protobuf.TaskState state = 8;</code>
   * @return The state.
   */
  com.platon.rosettanet.admin.grpc.service.TaskState getState();

  /**
   * <pre>
   * 任务失败原因
   * </pre>
   *
   * <code>string reason = 9;</code>
   * @return The reason.
   */
  java.lang.String getReason();
  /**
   * <pre>
   * 任务失败原因
   * </pre>
   *
   * <code>string reason = 9;</code>
   * @return The bytes for reason.
   */
  com.google.protobuf.ByteString
      getReasonBytes();

  /**
   * <pre>
   * 任务的事件个数
   * </pre>
   *
   * <code>uint32 event_count = 10;</code>
   * @return The eventCount.
   */
  int getEventCount();

  /**
   * <pre>
   * 任务描述(非必须)
   * </pre>
   *
   * <code>string desc = 11;</code>
   * @return The desc.
   */
  java.lang.String getDesc();
  /**
   * <pre>
   * 任务描述(非必须)
   * </pre>
   *
   * <code>string desc = 11;</code>
   * @return The bytes for desc.
   */
  com.google.protobuf.ByteString
      getDescBytes();

  /**
   * <pre>
   * 任务的发起时间戳 (单位: ms)
   * </pre>
   *
   * <code>uint64 create_at = 12;</code>
   * @return The createAt.
   */
  long getCreateAt();

  /**
   * <pre>
   * 任务的终止&lt;成功or失败&gt;时间戳 (单位: ms)
   * </pre>
   *
   * <code>uint64 end_at = 13;</code>
   * @return The endAt.
   */
  long getEndAt();

  /**
   * <pre>
   * 任务的开始执行时间戳 (单位: ms)
   * </pre>
   *
   * <code>uint64 start_at = 14;</code>
   * @return The startAt.
   */
  long getStartAt();

  /**
   * <pre>
   * 任务发起方的 partyId
   * </pre>
   *
   * <code>string party_id = 15;</code>
   * @return The partyId.
   */
  java.lang.String getPartyId();
  /**
   * <pre>
   * 任务发起方的 partyId
   * </pre>
   *
   * <code>string party_id = 15;</code>
   * @return The bytes for partyId.
   */
  com.google.protobuf.ByteString
      getPartyIdBytes();

  /**
   * <pre>
   * 任务的算法提供者信息
   * </pre>
   *
   * <code>.api.protobuf.TaskOrganization algo_supplier = 20;</code>
   * @return Whether the algoSupplier field is set.
   */
  boolean hasAlgoSupplier();
  /**
   * <pre>
   * 任务的算法提供者信息
   * </pre>
   *
   * <code>.api.protobuf.TaskOrganization algo_supplier = 20;</code>
   * @return The algoSupplier.
   */
  com.platon.rosettanet.admin.grpc.service.TaskOrganization getAlgoSupplier();
  /**
   * <pre>
   * 任务的算法提供者信息
   * </pre>
   *
   * <code>.api.protobuf.TaskOrganization algo_supplier = 20;</code>
   */
  com.platon.rosettanet.admin.grpc.service.TaskOrganizationOrBuilder getAlgoSupplierOrBuilder();

  /**
   * <pre>
   * 任务的初始资源声明
   * </pre>
   *
   * <code>.api.protobuf.TaskResourceCostDeclare operation_cost = 21;</code>
   * @return Whether the operationCost field is set.
   */
  boolean hasOperationCost();
  /**
   * <pre>
   * 任务的初始资源声明
   * </pre>
   *
   * <code>.api.protobuf.TaskResourceCostDeclare operation_cost = 21;</code>
   * @return The operationCost.
   */
  com.platon.rosettanet.admin.grpc.service.TaskResourceCostDeclare getOperationCost();
  /**
   * <pre>
   * 任务的初始资源声明
   * </pre>
   *
   * <code>.api.protobuf.TaskResourceCostDeclare operation_cost = 21;</code>
   */
  com.platon.rosettanet.admin.grpc.service.TaskResourceCostDeclareOrBuilder getOperationCostOrBuilder();

  /**
   * <pre>
   * 任务的数据提供方组信息 (可包含发起方和参与方)
   * </pre>
   *
   * <code>repeated .types.TaskDataSupplier data_suppliers = 22;</code>
   */
  java.util.List<com.platon.rosettanet.admin.grpc.service.TaskDataSupplier> 
      getDataSuppliersList();
  /**
   * <pre>
   * 任务的数据提供方组信息 (可包含发起方和参与方)
   * </pre>
   *
   * <code>repeated .types.TaskDataSupplier data_suppliers = 22;</code>
   */
  com.platon.rosettanet.admin.grpc.service.TaskDataSupplier getDataSuppliers(int index);
  /**
   * <pre>
   * 任务的数据提供方组信息 (可包含发起方和参与方)
   * </pre>
   *
   * <code>repeated .types.TaskDataSupplier data_suppliers = 22;</code>
   */
  int getDataSuppliersCount();
  /**
   * <pre>
   * 任务的数据提供方组信息 (可包含发起方和参与方)
   * </pre>
   *
   * <code>repeated .types.TaskDataSupplier data_suppliers = 22;</code>
   */
  java.util.List<? extends com.platon.rosettanet.admin.grpc.service.TaskDataSupplierOrBuilder> 
      getDataSuppliersOrBuilderList();
  /**
   * <pre>
   * 任务的数据提供方组信息 (可包含发起方和参与方)
   * </pre>
   *
   * <code>repeated .types.TaskDataSupplier data_suppliers = 22;</code>
   */
  com.platon.rosettanet.admin.grpc.service.TaskDataSupplierOrBuilder getDataSuppliersOrBuilder(
      int index);

  /**
   * <pre>
   * 任务的算力提供方组织信息 (可包含发起方和参与方)
   * </pre>
   *
   * <code>repeated .types.TaskPowerSupplier power_suppliers = 23;</code>
   */
  java.util.List<com.platon.rosettanet.admin.grpc.service.TaskPowerSupplier> 
      getPowerSuppliersList();
  /**
   * <pre>
   * 任务的算力提供方组织信息 (可包含发起方和参与方)
   * </pre>
   *
   * <code>repeated .types.TaskPowerSupplier power_suppliers = 23;</code>
   */
  com.platon.rosettanet.admin.grpc.service.TaskPowerSupplier getPowerSuppliers(int index);
  /**
   * <pre>
   * 任务的算力提供方组织信息 (可包含发起方和参与方)
   * </pre>
   *
   * <code>repeated .types.TaskPowerSupplier power_suppliers = 23;</code>
   */
  int getPowerSuppliersCount();
  /**
   * <pre>
   * 任务的算力提供方组织信息 (可包含发起方和参与方)
   * </pre>
   *
   * <code>repeated .types.TaskPowerSupplier power_suppliers = 23;</code>
   */
  java.util.List<? extends com.platon.rosettanet.admin.grpc.service.TaskPowerSupplierOrBuilder> 
      getPowerSuppliersOrBuilderList();
  /**
   * <pre>
   * 任务的算力提供方组织信息 (可包含发起方和参与方)
   * </pre>
   *
   * <code>repeated .types.TaskPowerSupplier power_suppliers = 23;</code>
   */
  com.platon.rosettanet.admin.grpc.service.TaskPowerSupplierOrBuilder getPowerSuppliersOrBuilder(
      int index);

  /**
   * <pre>
   * 任务的结果接收方组织信息 (可包含发起方和参与方)
   * </pre>
   *
   * <code>repeated .api.protobuf.TaskOrganization receivers = 24;</code>
   */
  java.util.List<com.platon.rosettanet.admin.grpc.service.TaskOrganization> 
      getReceiversList();
  /**
   * <pre>
   * 任务的结果接收方组织信息 (可包含发起方和参与方)
   * </pre>
   *
   * <code>repeated .api.protobuf.TaskOrganization receivers = 24;</code>
   */
  com.platon.rosettanet.admin.grpc.service.TaskOrganization getReceivers(int index);
  /**
   * <pre>
   * 任务的结果接收方组织信息 (可包含发起方和参与方)
   * </pre>
   *
   * <code>repeated .api.protobuf.TaskOrganization receivers = 24;</code>
   */
  int getReceiversCount();
  /**
   * <pre>
   * 任务的结果接收方组织信息 (可包含发起方和参与方)
   * </pre>
   *
   * <code>repeated .api.protobuf.TaskOrganization receivers = 24;</code>
   */
  java.util.List<? extends com.platon.rosettanet.admin.grpc.service.TaskOrganizationOrBuilder> 
      getReceiversOrBuilderList();
  /**
   * <pre>
   * 任务的结果接收方组织信息 (可包含发起方和参与方)
   * </pre>
   *
   * <code>repeated .api.protobuf.TaskOrganization receivers = 24;</code>
   */
  com.platon.rosettanet.admin.grpc.service.TaskOrganizationOrBuilder getReceiversOrBuilder(
      int index);

  /**
   * <pre>
   * 任务的所有产生事件列表
   * </pre>
   *
   * <code>repeated .types.TaskEvent task_events = 25;</code>
   */
  java.util.List<com.platon.rosettanet.admin.grpc.service.TaskEvent> 
      getTaskEventsList();
  /**
   * <pre>
   * 任务的所有产生事件列表
   * </pre>
   *
   * <code>repeated .types.TaskEvent task_events = 25;</code>
   */
  com.platon.rosettanet.admin.grpc.service.TaskEvent getTaskEvents(int index);
  /**
   * <pre>
   * 任务的所有产生事件列表
   * </pre>
   *
   * <code>repeated .types.TaskEvent task_events = 25;</code>
   */
  int getTaskEventsCount();
  /**
   * <pre>
   * 任务的所有产生事件列表
   * </pre>
   *
   * <code>repeated .types.TaskEvent task_events = 25;</code>
   */
  java.util.List<? extends com.platon.rosettanet.admin.grpc.service.TaskEventOrBuilder> 
      getTaskEventsOrBuilderList();
  /**
   * <pre>
   * 任务的所有产生事件列表
   * </pre>
   *
   * <code>repeated .types.TaskEvent task_events = 25;</code>
   */
  com.platon.rosettanet.admin.grpc.service.TaskEventOrBuilder getTaskEventsOrBuilder(
      int index);

  /**
   * <pre>
   * 任务的计算合约代码
   * </pre>
   *
   * <code>string calculate_contract_code = 26;</code>
   * @return The calculateContractCode.
   */
  java.lang.String getCalculateContractCode();
  /**
   * <pre>
   * 任务的计算合约代码
   * </pre>
   *
   * <code>string calculate_contract_code = 26;</code>
   * @return The bytes for calculateContractCode.
   */
  com.google.protobuf.ByteString
      getCalculateContractCodeBytes();

  /**
   * <pre>
   * 任务的数据分片合约代码
   * </pre>
   *
   * <code>string data_split_contract_code = 27;</code>
   * @return The dataSplitContractCode.
   */
  java.lang.String getDataSplitContractCode();
  /**
   * <pre>
   * 任务的数据分片合约代码
   * </pre>
   *
   * <code>string data_split_contract_code = 27;</code>
   * @return The bytes for dataSplitContractCode.
   */
  com.google.protobuf.ByteString
      getDataSplitContractCodeBytes();

  /**
   * <pre>
   * 任务的合约调用的额外可变入参 (json 字符串, 根据算法来)
   * </pre>
   *
   * <code>string contract_extra_params = 28;</code>
   * @return The contractExtraParams.
   */
  java.lang.String getContractExtraParams();
  /**
   * <pre>
   * 任务的合约调用的额外可变入参 (json 字符串, 根据算法来)
   * </pre>
   *
   * <code>string contract_extra_params = 28;</code>
   * @return The bytes for contractExtraParams.
   */
  com.google.protobuf.ByteString
      getContractExtraParamsBytes();

  /**
   * <pre>
   * v2.0
   * </pre>
   *
   * <code>string user = 29;</code>
   * @return The user.
   */
  java.lang.String getUser();
  /**
   * <pre>
   * v2.0
   * </pre>
   *
   * <code>string user = 29;</code>
   * @return The bytes for user.
   */
  com.google.protobuf.ByteString
      getUserBytes();

  /**
   * <pre>
   * 用户类型 (0: 未定义; 1: 以太坊地址; 2: Alaya地址; 3: PlatON地址)
   * </pre>
   *
   * <code>.api.protobuf.UserType user_type = 30;</code>
   * @return The enum numeric value on the wire for userType.
   */
  int getUserTypeValue();
  /**
   * <pre>
   * 用户类型 (0: 未定义; 1: 以太坊地址; 2: Alaya地址; 3: PlatON地址)
   * </pre>
   *
   * <code>.api.protobuf.UserType user_type = 30;</code>
   * @return The userType.
   */
  com.platon.rosettanet.admin.grpc.service.UserType getUserType();
}
