// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lib/common/base.proto

package com.platon.rosettanet.admin.grpc.service;

public interface TaskOrganizationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.protobuf.TaskOrganization)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string party_id = 1;</code>
   * @return The partyId.
   */
  java.lang.String getPartyId();
  /**
   * <code>string party_id = 1;</code>
   * @return The bytes for partyId.
   */
  com.google.protobuf.ByteString
      getPartyIdBytes();

  /**
   * <pre>
   * org name
   * </pre>
   *
   * <code>string node_name = 2;</code>
   * @return The nodeName.
   */
  java.lang.String getNodeName();
  /**
   * <pre>
   * org name
   * </pre>
   *
   * <code>string node_name = 2;</code>
   * @return The bytes for nodeName.
   */
  com.google.protobuf.ByteString
      getNodeNameBytes();

  /**
   * <pre>
   * the node_id for org
   * </pre>
   *
   * <code>string node_id = 3;</code>
   * @return The nodeId.
   */
  java.lang.String getNodeId();
  /**
   * <pre>
   * the node_id for org
   * </pre>
   *
   * <code>string node_id = 3;</code>
   * @return The bytes for nodeId.
   */
  com.google.protobuf.ByteString
      getNodeIdBytes();

  /**
   * <pre>
   * the identity for org
   * </pre>
   *
   * <code>string identity_id = 4;</code>
   * @return The identityId.
   */
  java.lang.String getIdentityId();
  /**
   * <pre>
   * the identity for org
   * </pre>
   *
   * <code>string identity_id = 4;</code>
   * @return The bytes for identityId.
   */
  com.google.protobuf.ByteString
      getIdentityIdBytes();
}
