// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lib/types/taskdata.proto

package com.platon.rosettanet.admin.grpc.service;

/**
 * <pre>
 * 任务算力提供方信息
 * </pre>
 *
 * Protobuf type {@code types.TaskPowerSupplier}
 */
public final class TaskPowerSupplier extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:types.TaskPowerSupplier)
    TaskPowerSupplierOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TaskPowerSupplier.newBuilder() to construct.
  private TaskPowerSupplier(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TaskPowerSupplier() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TaskPowerSupplier();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TaskPowerSupplier(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.platon.rosettanet.admin.grpc.service.TaskOrganization.Builder subBuilder = null;
            if (organization_ != null) {
              subBuilder = organization_.toBuilder();
            }
            organization_ = input.readMessage(com.platon.rosettanet.admin.grpc.service.TaskOrganization.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(organization_);
              organization_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.platon.rosettanet.admin.grpc.service.ResourceUsageOverview.Builder subBuilder = null;
            if (resourceUsedOverview_ != null) {
              subBuilder = resourceUsedOverview_.toBuilder();
            }
            resourceUsedOverview_ = input.readMessage(com.platon.rosettanet.admin.grpc.service.ResourceUsageOverview.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(resourceUsedOverview_);
              resourceUsedOverview_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.platon.rosettanet.admin.grpc.service.TaskDataProto.internal_static_types_TaskPowerSupplier_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.platon.rosettanet.admin.grpc.service.TaskDataProto.internal_static_types_TaskPowerSupplier_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.platon.rosettanet.admin.grpc.service.TaskPowerSupplier.class, com.platon.rosettanet.admin.grpc.service.TaskPowerSupplier.Builder.class);
  }

  public static final int ORGANIZATION_FIELD_NUMBER = 1;
  private com.platon.rosettanet.admin.grpc.service.TaskOrganization organization_;
  /**
   * <pre>
   * 身份信息
   * </pre>
   *
   * <code>.api.protobuf.TaskOrganization organization = 1;</code>
   * @return Whether the organization field is set.
   */
  @java.lang.Override
  public boolean hasOrganization() {
    return organization_ != null;
  }
  /**
   * <pre>
   * 身份信息
   * </pre>
   *
   * <code>.api.protobuf.TaskOrganization organization = 1;</code>
   * @return The organization.
   */
  @java.lang.Override
  public com.platon.rosettanet.admin.grpc.service.TaskOrganization getOrganization() {
    return organization_ == null ? com.platon.rosettanet.admin.grpc.service.TaskOrganization.getDefaultInstance() : organization_;
  }
  /**
   * <pre>
   * 身份信息
   * </pre>
   *
   * <code>.api.protobuf.TaskOrganization organization = 1;</code>
   */
  @java.lang.Override
  public com.platon.rosettanet.admin.grpc.service.TaskOrganizationOrBuilder getOrganizationOrBuilder() {
    return getOrganization();
  }

  public static final int RESOURCE_USED_OVERVIEW_FIELD_NUMBER = 2;
  private com.platon.rosettanet.admin.grpc.service.ResourceUsageOverview resourceUsedOverview_;
  /**
   * <pre>
   * 算力使用情况
   * </pre>
   *
   * <code>.types.ResourceUsageOverview resource_used_overview = 2;</code>
   * @return Whether the resourceUsedOverview field is set.
   */
  @java.lang.Override
  public boolean hasResourceUsedOverview() {
    return resourceUsedOverview_ != null;
  }
  /**
   * <pre>
   * 算力使用情况
   * </pre>
   *
   * <code>.types.ResourceUsageOverview resource_used_overview = 2;</code>
   * @return The resourceUsedOverview.
   */
  @java.lang.Override
  public com.platon.rosettanet.admin.grpc.service.ResourceUsageOverview getResourceUsedOverview() {
    return resourceUsedOverview_ == null ? com.platon.rosettanet.admin.grpc.service.ResourceUsageOverview.getDefaultInstance() : resourceUsedOverview_;
  }
  /**
   * <pre>
   * 算力使用情况
   * </pre>
   *
   * <code>.types.ResourceUsageOverview resource_used_overview = 2;</code>
   */
  @java.lang.Override
  public com.platon.rosettanet.admin.grpc.service.ResourceUsageOverviewOrBuilder getResourceUsedOverviewOrBuilder() {
    return getResourceUsedOverview();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (organization_ != null) {
      output.writeMessage(1, getOrganization());
    }
    if (resourceUsedOverview_ != null) {
      output.writeMessage(2, getResourceUsedOverview());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (organization_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getOrganization());
    }
    if (resourceUsedOverview_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getResourceUsedOverview());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.platon.rosettanet.admin.grpc.service.TaskPowerSupplier)) {
      return super.equals(obj);
    }
    com.platon.rosettanet.admin.grpc.service.TaskPowerSupplier other = (com.platon.rosettanet.admin.grpc.service.TaskPowerSupplier) obj;

    if (hasOrganization() != other.hasOrganization()) return false;
    if (hasOrganization()) {
      if (!getOrganization()
          .equals(other.getOrganization())) return false;
    }
    if (hasResourceUsedOverview() != other.hasResourceUsedOverview()) return false;
    if (hasResourceUsedOverview()) {
      if (!getResourceUsedOverview()
          .equals(other.getResourceUsedOverview())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasOrganization()) {
      hash = (37 * hash) + ORGANIZATION_FIELD_NUMBER;
      hash = (53 * hash) + getOrganization().hashCode();
    }
    if (hasResourceUsedOverview()) {
      hash = (37 * hash) + RESOURCE_USED_OVERVIEW_FIELD_NUMBER;
      hash = (53 * hash) + getResourceUsedOverview().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.platon.rosettanet.admin.grpc.service.TaskPowerSupplier parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.platon.rosettanet.admin.grpc.service.TaskPowerSupplier parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.platon.rosettanet.admin.grpc.service.TaskPowerSupplier parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.platon.rosettanet.admin.grpc.service.TaskPowerSupplier parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.platon.rosettanet.admin.grpc.service.TaskPowerSupplier parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.platon.rosettanet.admin.grpc.service.TaskPowerSupplier parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.platon.rosettanet.admin.grpc.service.TaskPowerSupplier parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.platon.rosettanet.admin.grpc.service.TaskPowerSupplier parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.platon.rosettanet.admin.grpc.service.TaskPowerSupplier parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.platon.rosettanet.admin.grpc.service.TaskPowerSupplier parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.platon.rosettanet.admin.grpc.service.TaskPowerSupplier parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.platon.rosettanet.admin.grpc.service.TaskPowerSupplier parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.platon.rosettanet.admin.grpc.service.TaskPowerSupplier prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 任务算力提供方信息
   * </pre>
   *
   * Protobuf type {@code types.TaskPowerSupplier}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:types.TaskPowerSupplier)
      com.platon.rosettanet.admin.grpc.service.TaskPowerSupplierOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.platon.rosettanet.admin.grpc.service.TaskDataProto.internal_static_types_TaskPowerSupplier_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.platon.rosettanet.admin.grpc.service.TaskDataProto.internal_static_types_TaskPowerSupplier_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.platon.rosettanet.admin.grpc.service.TaskPowerSupplier.class, com.platon.rosettanet.admin.grpc.service.TaskPowerSupplier.Builder.class);
    }

    // Construct using com.platon.rosettanet.admin.grpc.service.TaskPowerSupplier.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (organizationBuilder_ == null) {
        organization_ = null;
      } else {
        organization_ = null;
        organizationBuilder_ = null;
      }
      if (resourceUsedOverviewBuilder_ == null) {
        resourceUsedOverview_ = null;
      } else {
        resourceUsedOverview_ = null;
        resourceUsedOverviewBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.platon.rosettanet.admin.grpc.service.TaskDataProto.internal_static_types_TaskPowerSupplier_descriptor;
    }

    @java.lang.Override
    public com.platon.rosettanet.admin.grpc.service.TaskPowerSupplier getDefaultInstanceForType() {
      return com.platon.rosettanet.admin.grpc.service.TaskPowerSupplier.getDefaultInstance();
    }

    @java.lang.Override
    public com.platon.rosettanet.admin.grpc.service.TaskPowerSupplier build() {
      com.platon.rosettanet.admin.grpc.service.TaskPowerSupplier result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.platon.rosettanet.admin.grpc.service.TaskPowerSupplier buildPartial() {
      com.platon.rosettanet.admin.grpc.service.TaskPowerSupplier result = new com.platon.rosettanet.admin.grpc.service.TaskPowerSupplier(this);
      if (organizationBuilder_ == null) {
        result.organization_ = organization_;
      } else {
        result.organization_ = organizationBuilder_.build();
      }
      if (resourceUsedOverviewBuilder_ == null) {
        result.resourceUsedOverview_ = resourceUsedOverview_;
      } else {
        result.resourceUsedOverview_ = resourceUsedOverviewBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.platon.rosettanet.admin.grpc.service.TaskPowerSupplier) {
        return mergeFrom((com.platon.rosettanet.admin.grpc.service.TaskPowerSupplier)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.platon.rosettanet.admin.grpc.service.TaskPowerSupplier other) {
      if (other == com.platon.rosettanet.admin.grpc.service.TaskPowerSupplier.getDefaultInstance()) return this;
      if (other.hasOrganization()) {
        mergeOrganization(other.getOrganization());
      }
      if (other.hasResourceUsedOverview()) {
        mergeResourceUsedOverview(other.getResourceUsedOverview());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.platon.rosettanet.admin.grpc.service.TaskPowerSupplier parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.platon.rosettanet.admin.grpc.service.TaskPowerSupplier) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.platon.rosettanet.admin.grpc.service.TaskOrganization organization_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.platon.rosettanet.admin.grpc.service.TaskOrganization, com.platon.rosettanet.admin.grpc.service.TaskOrganization.Builder, com.platon.rosettanet.admin.grpc.service.TaskOrganizationOrBuilder> organizationBuilder_;
    /**
     * <pre>
     * 身份信息
     * </pre>
     *
     * <code>.api.protobuf.TaskOrganization organization = 1;</code>
     * @return Whether the organization field is set.
     */
    public boolean hasOrganization() {
      return organizationBuilder_ != null || organization_ != null;
    }
    /**
     * <pre>
     * 身份信息
     * </pre>
     *
     * <code>.api.protobuf.TaskOrganization organization = 1;</code>
     * @return The organization.
     */
    public com.platon.rosettanet.admin.grpc.service.TaskOrganization getOrganization() {
      if (organizationBuilder_ == null) {
        return organization_ == null ? com.platon.rosettanet.admin.grpc.service.TaskOrganization.getDefaultInstance() : organization_;
      } else {
        return organizationBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 身份信息
     * </pre>
     *
     * <code>.api.protobuf.TaskOrganization organization = 1;</code>
     */
    public Builder setOrganization(com.platon.rosettanet.admin.grpc.service.TaskOrganization value) {
      if (organizationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        organization_ = value;
        onChanged();
      } else {
        organizationBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 身份信息
     * </pre>
     *
     * <code>.api.protobuf.TaskOrganization organization = 1;</code>
     */
    public Builder setOrganization(
        com.platon.rosettanet.admin.grpc.service.TaskOrganization.Builder builderForValue) {
      if (organizationBuilder_ == null) {
        organization_ = builderForValue.build();
        onChanged();
      } else {
        organizationBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 身份信息
     * </pre>
     *
     * <code>.api.protobuf.TaskOrganization organization = 1;</code>
     */
    public Builder mergeOrganization(com.platon.rosettanet.admin.grpc.service.TaskOrganization value) {
      if (organizationBuilder_ == null) {
        if (organization_ != null) {
          organization_ =
            com.platon.rosettanet.admin.grpc.service.TaskOrganization.newBuilder(organization_).mergeFrom(value).buildPartial();
        } else {
          organization_ = value;
        }
        onChanged();
      } else {
        organizationBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 身份信息
     * </pre>
     *
     * <code>.api.protobuf.TaskOrganization organization = 1;</code>
     */
    public Builder clearOrganization() {
      if (organizationBuilder_ == null) {
        organization_ = null;
        onChanged();
      } else {
        organization_ = null;
        organizationBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 身份信息
     * </pre>
     *
     * <code>.api.protobuf.TaskOrganization organization = 1;</code>
     */
    public com.platon.rosettanet.admin.grpc.service.TaskOrganization.Builder getOrganizationBuilder() {
      
      onChanged();
      return getOrganizationFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 身份信息
     * </pre>
     *
     * <code>.api.protobuf.TaskOrganization organization = 1;</code>
     */
    public com.platon.rosettanet.admin.grpc.service.TaskOrganizationOrBuilder getOrganizationOrBuilder() {
      if (organizationBuilder_ != null) {
        return organizationBuilder_.getMessageOrBuilder();
      } else {
        return organization_ == null ?
            com.platon.rosettanet.admin.grpc.service.TaskOrganization.getDefaultInstance() : organization_;
      }
    }
    /**
     * <pre>
     * 身份信息
     * </pre>
     *
     * <code>.api.protobuf.TaskOrganization organization = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.platon.rosettanet.admin.grpc.service.TaskOrganization, com.platon.rosettanet.admin.grpc.service.TaskOrganization.Builder, com.platon.rosettanet.admin.grpc.service.TaskOrganizationOrBuilder> 
        getOrganizationFieldBuilder() {
      if (organizationBuilder_ == null) {
        organizationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.platon.rosettanet.admin.grpc.service.TaskOrganization, com.platon.rosettanet.admin.grpc.service.TaskOrganization.Builder, com.platon.rosettanet.admin.grpc.service.TaskOrganizationOrBuilder>(
                getOrganization(),
                getParentForChildren(),
                isClean());
        organization_ = null;
      }
      return organizationBuilder_;
    }

    private com.platon.rosettanet.admin.grpc.service.ResourceUsageOverview resourceUsedOverview_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.platon.rosettanet.admin.grpc.service.ResourceUsageOverview, com.platon.rosettanet.admin.grpc.service.ResourceUsageOverview.Builder, com.platon.rosettanet.admin.grpc.service.ResourceUsageOverviewOrBuilder> resourceUsedOverviewBuilder_;
    /**
     * <pre>
     * 算力使用情况
     * </pre>
     *
     * <code>.types.ResourceUsageOverview resource_used_overview = 2;</code>
     * @return Whether the resourceUsedOverview field is set.
     */
    public boolean hasResourceUsedOverview() {
      return resourceUsedOverviewBuilder_ != null || resourceUsedOverview_ != null;
    }
    /**
     * <pre>
     * 算力使用情况
     * </pre>
     *
     * <code>.types.ResourceUsageOverview resource_used_overview = 2;</code>
     * @return The resourceUsedOverview.
     */
    public com.platon.rosettanet.admin.grpc.service.ResourceUsageOverview getResourceUsedOverview() {
      if (resourceUsedOverviewBuilder_ == null) {
        return resourceUsedOverview_ == null ? com.platon.rosettanet.admin.grpc.service.ResourceUsageOverview.getDefaultInstance() : resourceUsedOverview_;
      } else {
        return resourceUsedOverviewBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 算力使用情况
     * </pre>
     *
     * <code>.types.ResourceUsageOverview resource_used_overview = 2;</code>
     */
    public Builder setResourceUsedOverview(com.platon.rosettanet.admin.grpc.service.ResourceUsageOverview value) {
      if (resourceUsedOverviewBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        resourceUsedOverview_ = value;
        onChanged();
      } else {
        resourceUsedOverviewBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 算力使用情况
     * </pre>
     *
     * <code>.types.ResourceUsageOverview resource_used_overview = 2;</code>
     */
    public Builder setResourceUsedOverview(
        com.platon.rosettanet.admin.grpc.service.ResourceUsageOverview.Builder builderForValue) {
      if (resourceUsedOverviewBuilder_ == null) {
        resourceUsedOverview_ = builderForValue.build();
        onChanged();
      } else {
        resourceUsedOverviewBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 算力使用情况
     * </pre>
     *
     * <code>.types.ResourceUsageOverview resource_used_overview = 2;</code>
     */
    public Builder mergeResourceUsedOverview(com.platon.rosettanet.admin.grpc.service.ResourceUsageOverview value) {
      if (resourceUsedOverviewBuilder_ == null) {
        if (resourceUsedOverview_ != null) {
          resourceUsedOverview_ =
            com.platon.rosettanet.admin.grpc.service.ResourceUsageOverview.newBuilder(resourceUsedOverview_).mergeFrom(value).buildPartial();
        } else {
          resourceUsedOverview_ = value;
        }
        onChanged();
      } else {
        resourceUsedOverviewBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 算力使用情况
     * </pre>
     *
     * <code>.types.ResourceUsageOverview resource_used_overview = 2;</code>
     */
    public Builder clearResourceUsedOverview() {
      if (resourceUsedOverviewBuilder_ == null) {
        resourceUsedOverview_ = null;
        onChanged();
      } else {
        resourceUsedOverview_ = null;
        resourceUsedOverviewBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 算力使用情况
     * </pre>
     *
     * <code>.types.ResourceUsageOverview resource_used_overview = 2;</code>
     */
    public com.platon.rosettanet.admin.grpc.service.ResourceUsageOverview.Builder getResourceUsedOverviewBuilder() {
      
      onChanged();
      return getResourceUsedOverviewFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 算力使用情况
     * </pre>
     *
     * <code>.types.ResourceUsageOverview resource_used_overview = 2;</code>
     */
    public com.platon.rosettanet.admin.grpc.service.ResourceUsageOverviewOrBuilder getResourceUsedOverviewOrBuilder() {
      if (resourceUsedOverviewBuilder_ != null) {
        return resourceUsedOverviewBuilder_.getMessageOrBuilder();
      } else {
        return resourceUsedOverview_ == null ?
            com.platon.rosettanet.admin.grpc.service.ResourceUsageOverview.getDefaultInstance() : resourceUsedOverview_;
      }
    }
    /**
     * <pre>
     * 算力使用情况
     * </pre>
     *
     * <code>.types.ResourceUsageOverview resource_used_overview = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.platon.rosettanet.admin.grpc.service.ResourceUsageOverview, com.platon.rosettanet.admin.grpc.service.ResourceUsageOverview.Builder, com.platon.rosettanet.admin.grpc.service.ResourceUsageOverviewOrBuilder> 
        getResourceUsedOverviewFieldBuilder() {
      if (resourceUsedOverviewBuilder_ == null) {
        resourceUsedOverviewBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.platon.rosettanet.admin.grpc.service.ResourceUsageOverview, com.platon.rosettanet.admin.grpc.service.ResourceUsageOverview.Builder, com.platon.rosettanet.admin.grpc.service.ResourceUsageOverviewOrBuilder>(
                getResourceUsedOverview(),
                getParentForChildren(),
                isClean());
        resourceUsedOverview_ = null;
      }
      return resourceUsedOverviewBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:types.TaskPowerSupplier)
  }

  // @@protoc_insertion_point(class_scope:types.TaskPowerSupplier)
  private static final com.platon.rosettanet.admin.grpc.service.TaskPowerSupplier DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.platon.rosettanet.admin.grpc.service.TaskPowerSupplier();
  }

  public static com.platon.rosettanet.admin.grpc.service.TaskPowerSupplier getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TaskPowerSupplier>
      PARSER = new com.google.protobuf.AbstractParser<TaskPowerSupplier>() {
    @java.lang.Override
    public TaskPowerSupplier parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TaskPowerSupplier(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TaskPowerSupplier> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TaskPowerSupplier> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.platon.rosettanet.admin.grpc.service.TaskPowerSupplier getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

