// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lib/types/taskdata.proto

package com.platon.rosettanet.admin.grpc.service;

public interface TaskDataSupplierOrBuilder extends
    // @@protoc_insertion_point(interface_extends:types.TaskDataSupplier)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 身份信息
   * </pre>
   *
   * <code>.api.protobuf.TaskOrganization organization = 1;</code>
   * @return Whether the organization field is set.
   */
  boolean hasOrganization();
  /**
   * <pre>
   * 身份信息
   * </pre>
   *
   * <code>.api.protobuf.TaskOrganization organization = 1;</code>
   * @return The organization.
   */
  com.platon.rosettanet.admin.grpc.service.TaskOrganization getOrganization();
  /**
   * <pre>
   * 身份信息
   * </pre>
   *
   * <code>.api.protobuf.TaskOrganization organization = 1;</code>
   */
  com.platon.rosettanet.admin.grpc.service.TaskOrganizationOrBuilder getOrganizationOrBuilder();

  /**
   * <pre>
   * 元数据Id
   * </pre>
   *
   * <code>string metadata_id = 2;</code>
   * @return The metadataId.
   */
  java.lang.String getMetadataId();
  /**
   * <pre>
   * 元数据Id
   * </pre>
   *
   * <code>string metadata_id = 2;</code>
   * @return The bytes for metadataId.
   */
  com.google.protobuf.ByteString
      getMetadataIdBytes();

  /**
   * <pre>
   * 元数据名称
   * </pre>
   *
   * <code>string metadata_name = 3;</code>
   * @return The metadataName.
   */
  java.lang.String getMetadataName();
  /**
   * <pre>
   * 元数据名称
   * </pre>
   *
   * <code>string metadata_name = 3;</code>
   * @return The bytes for metadataName.
   */
  com.google.protobuf.ByteString
      getMetadataNameBytes();

  /**
   * <code>repeated .types.MetadataColumn columns = 4;</code>
   */
  java.util.List<com.platon.rosettanet.admin.grpc.service.MetadataColumn> 
      getColumnsList();
  /**
   * <code>repeated .types.MetadataColumn columns = 4;</code>
   */
  com.platon.rosettanet.admin.grpc.service.MetadataColumn getColumns(int index);
  /**
   * <code>repeated .types.MetadataColumn columns = 4;</code>
   */
  int getColumnsCount();
  /**
   * <code>repeated .types.MetadataColumn columns = 4;</code>
   */
  java.util.List<? extends com.platon.rosettanet.admin.grpc.service.MetadataColumnOrBuilder> 
      getColumnsOrBuilderList();
  /**
   * <code>repeated .types.MetadataColumn columns = 4;</code>
   */
  com.platon.rosettanet.admin.grpc.service.MetadataColumnOrBuilder getColumnsOrBuilder(
      int index);
}
