// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lib/common/base.proto

package com.platon.rosettanet.admin.grpc.service;

/**
 * <pre>
 * 本组织在task中的角色
 * </pre>
 *
 * Protobuf enum {@code api.protobuf.TaskRole}
 */
public enum TaskRole
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * 未知的任务角色
   * </pre>
   *
   * <code>TaskRole_Unknown = 0;</code>
   */
  TaskRole_Unknown(0),
  /**
   * <pre>
   * 任务发起方
   * </pre>
   *
   * <code>TaskRole_Sender = 1;</code>
   */
  TaskRole_Sender(1),
  /**
   * <pre>
   * 数据提供方
   * </pre>
   *
   * <code>TaskRole_DataSupplier = 2;</code>
   */
  TaskRole_DataSupplier(2),
  /**
   * <pre>
   * 算力提供方
   * </pre>
   *
   * <code>TaskRole_PowerSupplier = 3;</code>
   */
  TaskRole_PowerSupplier(3),
  /**
   * <pre>
   * 结果接收方
   * </pre>
   *
   * <code>TaskRole_Receiver = 4;</code>
   */
  TaskRole_Receiver(4),
  /**
   * <pre>
   * 算法提供方
   * </pre>
   *
   * <code>TaskRole_AlgoSupplier = 5;</code>
   */
  TaskRole_AlgoSupplier(5),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * 未知的任务角色
   * </pre>
   *
   * <code>TaskRole_Unknown = 0;</code>
   */
  public static final int TaskRole_Unknown_VALUE = 0;
  /**
   * <pre>
   * 任务发起方
   * </pre>
   *
   * <code>TaskRole_Sender = 1;</code>
   */
  public static final int TaskRole_Sender_VALUE = 1;
  /**
   * <pre>
   * 数据提供方
   * </pre>
   *
   * <code>TaskRole_DataSupplier = 2;</code>
   */
  public static final int TaskRole_DataSupplier_VALUE = 2;
  /**
   * <pre>
   * 算力提供方
   * </pre>
   *
   * <code>TaskRole_PowerSupplier = 3;</code>
   */
  public static final int TaskRole_PowerSupplier_VALUE = 3;
  /**
   * <pre>
   * 结果接收方
   * </pre>
   *
   * <code>TaskRole_Receiver = 4;</code>
   */
  public static final int TaskRole_Receiver_VALUE = 4;
  /**
   * <pre>
   * 算法提供方
   * </pre>
   *
   * <code>TaskRole_AlgoSupplier = 5;</code>
   */
  public static final int TaskRole_AlgoSupplier_VALUE = 5;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static TaskRole valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static TaskRole forNumber(int value) {
    switch (value) {
      case 0: return TaskRole_Unknown;
      case 1: return TaskRole_Sender;
      case 2: return TaskRole_DataSupplier;
      case 3: return TaskRole_PowerSupplier;
      case 4: return TaskRole_Receiver;
      case 5: return TaskRole_AlgoSupplier;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<TaskRole>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      TaskRole> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<TaskRole>() {
          public TaskRole findValueByNumber(int number) {
            return TaskRole.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.platon.rosettanet.admin.grpc.service.Base.getDescriptor().getEnumTypes().get(8);
  }

  private static final TaskRole[] VALUES = values();

  public static TaskRole valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private TaskRole(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:api.protobuf.TaskRole)
}

