// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lib/common/base.proto

package com.platon.rosettanet.admin.grpc.service;

/**
 * <pre>
 * task的状态
 * </pre>
 *
 * Protobuf enum {@code api.protobuf.TaskState}
 */
public enum TaskState
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * 未知
   * </pre>
   *
   * <code>TaskState_Unknown = 0;</code>
   */
  TaskState_Unknown(0),
  /**
   * <pre>
   * 等在中
   * </pre>
   *
   * <code>TaskState_Pending = 1;</code>
   */
  TaskState_Pending(1),
  /**
   * <pre>
   * 计算中
   * </pre>
   *
   * <code>TaskState_Running = 2;</code>
   */
  TaskState_Running(2),
  /**
   * <pre>
   * 失败
   * </pre>
   *
   * <code>TaskState_Failed = 3;</code>
   */
  TaskState_Failed(3),
  /**
   * <pre>
   * 成功
   * </pre>
   *
   * <code>TaskState_Succeed = 4;</code>
   */
  TaskState_Succeed(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * 未知
   * </pre>
   *
   * <code>TaskState_Unknown = 0;</code>
   */
  public static final int TaskState_Unknown_VALUE = 0;
  /**
   * <pre>
   * 等在中
   * </pre>
   *
   * <code>TaskState_Pending = 1;</code>
   */
  public static final int TaskState_Pending_VALUE = 1;
  /**
   * <pre>
   * 计算中
   * </pre>
   *
   * <code>TaskState_Running = 2;</code>
   */
  public static final int TaskState_Running_VALUE = 2;
  /**
   * <pre>
   * 失败
   * </pre>
   *
   * <code>TaskState_Failed = 3;</code>
   */
  public static final int TaskState_Failed_VALUE = 3;
  /**
   * <pre>
   * 成功
   * </pre>
   *
   * <code>TaskState_Succeed = 4;</code>
   */
  public static final int TaskState_Succeed_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static TaskState valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static TaskState forNumber(int value) {
    switch (value) {
      case 0: return TaskState_Unknown;
      case 1: return TaskState_Pending;
      case 2: return TaskState_Running;
      case 3: return TaskState_Failed;
      case 4: return TaskState_Succeed;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<TaskState>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      TaskState> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<TaskState>() {
          public TaskState findValueByNumber(int number) {
            return TaskState.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.platon.rosettanet.admin.grpc.service.Base.getDescriptor().getEnumTypes().get(9);
  }

  private static final TaskState[] VALUES = values();

  public static TaskState valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private TaskState(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:api.protobuf.TaskState)
}

