// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lib/common/base.proto

package com.platon.rosettanet.admin.grpc.service;

/**
 * Protobuf enum {@code api.protobuf.UserType}
 */
public enum UserType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>User_Unknown = 0;</code>
   */
  User_Unknown(0),
  /**
   * <code>User_ETH = 1;</code>
   */
  User_ETH(1),
  /**
   * <code>User_ATP = 2;</code>
   */
  User_ATP(2),
  /**
   * <code>User_LAT = 3;</code>
   */
  User_LAT(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>User_Unknown = 0;</code>
   */
  public static final int User_Unknown_VALUE = 0;
  /**
   * <code>User_ETH = 1;</code>
   */
  public static final int User_ETH_VALUE = 1;
  /**
   * <code>User_ATP = 2;</code>
   */
  public static final int User_ATP_VALUE = 2;
  /**
   * <code>User_LAT = 3;</code>
   */
  public static final int User_LAT_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static UserType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static UserType forNumber(int value) {
    switch (value) {
      case 0: return User_Unknown;
      case 1: return User_ETH;
      case 2: return User_ATP;
      case 3: return User_LAT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<UserType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      UserType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<UserType>() {
          public UserType findValueByNumber(int number) {
            return UserType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.platon.rosettanet.admin.grpc.service.Base.getDescriptor().getEnumTypes().get(0);
  }

  private static final UserType[] VALUES = values();

  public static UserType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private UserType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:api.protobuf.UserType)
}

